"""Generate sfxtable.c from the engine's own tables. Never hand edit sfxtable.c."""
import json, os
here = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(here + "/tables.json"))
voc, vox, themes = d["voc"], d["vox"], d["themes"]
varuse = json.load(open(here + "/varuse.json"))   # index -> 1 infantry, 2 vehicle, 3 both

out = []
w = out.append
w("/* sfxtable.c -- GENERATED by tools/gen_sfxtable.py from the vanilla Tiberian Dawn")
w(" * source. VocType names and priorities come from tiberiandawn/audio.cpp")
w(" * SoundEffectName[], VoxType names from Speech[], theme names and durations from")
w(" * theme.cpp _themes[]. Regenerate, do not hand edit. */")
w("")
w('#include "sfxtable.h"')
w("")
w("const SfxEntry sfx_voc[SFX_VOC_COUNT] = {")
for i, e in enumerate(voc):
    where = {"IN_NOVAR": "SFX_NOVAR", "IN_JUV": "SFX_JUV", "IN_VAR": "SFX_VAR"}[e["where"]]
    w('    {"%s", %d, %s, %d},' % (e["name"], e["priority"], where, varuse.get(str(i), 0)))
w("};")
w("")
w("const char *const sfx_vox[SFX_VOX_COUNT] = {")
for n in vox:
    w('    "%s",' % n)
w("};")
w("")
# THE FULL SCORE NAMES, for the jukebox. theme.cpp's table stores a TEXT NUMBER
# (TXT_THEME_*) and ThemeClass::Full_Name resolves it through Text_String against
# CONQUER.ENG. We do not need the archive: conquer.h carries the English text in the
# comment beside every #define, which is the same string the .ENG holds, and it is the
# engine's own header rather than a transcription of it.
#     #define TXT_THEME_AOI    191 // Act On Instinct
import re as _re
_SRC = os.path.normpath(os.path.join(here, "..", "..", "brain", "vanilla", "tiberiandawn"))
_txt = {}
for _line in open(os.path.join(_SRC, "conquer.h"), encoding="latin-1"):
    _m = _re.match(r"\s*#define\s+(TXT_\w+)\s+(\d+)\s*//\s*(.+?)\s*$", _line)
    if _m:
        _txt[_m.group(1)] = _m.group(3)
_missing = [t["fields"][0] for t in themes if t["fields"][0] not in _txt]
assert not _missing, ("conquer.h has no English text for %s -- the jukebox would show a "
                      "blank row, so this is a failed generation rather than a fallback"
                      % _missing)

w("const ThemeEntry sfx_theme[SFX_THEME_COUNT] = {")
for t in themes:
    f = t["fields"]
    # fields: Fullname, Scenario, Duration, Normal, Variation, Repeat, Available
    scen, dur = int(f[1]), int(f[2])
    normal = 1 if f[3] == "true" else 0
    variation = 1 if f[4] == "true" else 0
    repeat = 1 if f[5] == "true" else 0
    full = _txt[f[0]].replace('"', '\\"')
    w('    {"%s", %d, %d, %d, %d, %d, "%s"},'
      % (t["name"], scen, dur, normal, variation, repeat, full))
w("};")
w("")

hdr = []
h = hdr.append
h("/*")
h(" * sfxtable.h -- the engine's own sound tables, lifted from the GPL Tiberian Dawn")
h(" * source so the audio side never has to guess a filename.")
h(" *")
h(" * sfx_voc[] is indexed by the SFXIndex the sound callback hands over; the name is")
h(" * the base filename with no extension, and `where` says which extension rule")
h(" * applies (see sfx_voc_filename).")
h(" * sfx_vox[] is indexed by SpeechIndex and the file is always NAME.AUD.")
h(" */")
h("")
h("#ifndef SFXTABLE_H")
h("#define SFXTABLE_H")
h("")
h("#define SFX_VOC_COUNT %d" % len(voc))
h("#define SFX_VOX_COUNT %d" % len(vox))
h("#define SFX_THEME_COUNT %d" % len(themes))
h("")
h("typedef enum")
h("{")
h("    SFX_NOVAR = 0, /* NAME.AUD, always                                    */")
h("    SFX_JUV,       /* NAME.JUV when the juvenile option is on, else .AUD  */")
h("    SFX_VAR        /* NAME.V00 .. .V03 chosen by the variation number     */")
h("} SfxWhere;")
h("")
h("typedef struct")
h("{")
h("    const char *name;")
h("    int priority;")
h("    SfxWhere where;")
h("    int varuse; /* bit 0: asked with a positive variation (infantry .V01/.V03)  */")
h("               /* bit 1: asked with a negative variation (vehicles .V00/.V02) */")
h("               /* 0 means no response table ever names it                     */")
h("} SfxEntry;")
h("")
h("typedef struct")
h("{")
h("    const char *name;")
h("    int scenario;  /* first scenario the track becomes available in */")
h("    int duration;  /* seconds, as the 1995 table claims             */")
h("    int normal;    /* allowed in ordinary play                      */")
h("    int variation; /* a NAME.VAR alternate exists                   */")
h("    int repeat;    /* always loops                                  */")
h("    const char *fullname; /* the 1995 score name, CONQUER.ENG via TXT_THEME_* */")
h("} ThemeEntry;")
h("")
h("extern const SfxEntry sfx_voc[SFX_VOC_COUNT];")
h("extern const char *const sfx_vox[SFX_VOX_COUNT];")
h("extern const ThemeEntry sfx_theme[SFX_THEME_COUNT];")
h("")
h("/* Builds the filename the 1995 engine would have asked MFCD for. `variation` is")
h(" * the value from the sound callback; `juvenile` is Special.IsJuvenile. */")
h("void sfx_voc_filename(int index, int variation, int juvenile, char *out, int outlen);")
h("")
h("#endif /* SFXTABLE_H */")

open(here + "/../sfxtable.c", "w").write("\n".join(out) + "\n")
open(here + "/../sfxtable.h", "w").write("\n".join(hdr) + "\n")
print("wrote sfxtable.h/.c: voc=%d vox=%d themes=%d" % (len(voc), len(vox), len(themes)))
