/* GENERATED by game/bake_dosnames.py -- do not hand-edit.

   The readable name of every buildable, for the sidebar's tooltip. Every
   string here was read out of the game's own CONQUER.ENG inside
   data/dosdata/LOCAL.MIX rather than typed from memory, joined to the INI
   idents through the TXT_ ids on the type constructors in bdata/idata/
   udata/aadata.cpp.

   It is baked rather than exported because the brain cannot answer the
   question: Full_Name() returns a text id, and Text_String() reads a table
   the DLL front end never initialises. See bake_dosnames.py.

   113 buildables, 5 chrome labels, 0 missing.
*/
#ifndef DOSNAMES_H
#define DOSNAMES_H

struct DosName { const char* asset; const char* title; };

static const DosName DOSNAMES[] = {
    { "A10", "A10" },                    /* TXT_A10 */
    { "AFLD", "Airstrip" },              /* TXT_AIRSTRIP */
    { "APC", "APC" },                    /* TXT_APC */
    { "ARCO", "Oil Tanker" },            /* TXT_TANKER */
    { "ARTY", "Artillery" },             /* TXT_ARTY */
    { "ATWR", "Advanced Guard Tower" },  /* TXT_AGUARD_TOWER */
    { "BARB", "Barbwire Fence" },        /* TXT_BARBWIRE_WALL */
    { "BGGY", "Nod Buggy" },             /* TXT_DUNE_BUGGY */
    { "BIKE", "Recon Bike" },            /* TXT_BIKE */
    { "BIO", "Bio-Research Laboratory" }, /* TXT_BIO_LAB */
    { "BOAT", "Gun Boat" },              /* TXT_GUNBOAT */
    { "BRIK", "Concrete Wall" },         /* TXT_BRICK_WALL */
    { "C1", "Joe" },                     /* TXT_C1 */
    { "C10", "Nikoomba" },               /* TXT_C10 */
    { "C17", "C17" },                    /* TXT_C17 */
    { "C2", "Bill" },                    /* TXT_C2 */
    { "C3", "Shelly" },                  /* TXT_C3 */
    { "C4", "Maria" },                   /* TXT_C4 */
    { "C5", "Eydie" },                   /* TXT_C5 */
    { "C6", "Dave" },                    /* TXT_C6 */
    { "C7", "Phil" },                    /* TXT_C7 */
    { "C8", "Dwight" },                  /* TXT_C8 */
    { "C9", "Erik" },                    /* TXT_C9 */
    { "CHAN", "Dr. Chan" },              /* TXT_CHAN */
    { "CYCL", "Chain Link Fence" },      /* TXT_CYCLONE_WALL */
    { "DELPHI", "Agent Delphi" },        /* TXT_DELPHI */
    { "E1", "Minigunner" },              /* TXT_E1 */
    { "E2", "Grenadier" },               /* TXT_E2 */
    { "E3", "Bazooka" },                 /* TXT_E3 */
    { "E4", "Flamethrower" },            /* TXT_E4 */
    { "E5", "Chem-warrior" },            /* TXT_E5 */
    { "E6", "Engineer" },                /* TXT_E7 */
    { "EYE", "Advanced Com. Center" },   /* TXT_EYE */
    { "FACT", "Construction Yard" },     /* TXT_CONST_YARD */
    { "FIX", "Repair Bay" },             /* TXT_FIX_IT */
    { "FTNK", "Flame Tank" },            /* TXT_FTANK */
    { "GTWR", "Guard Tower" },           /* TXT_GUARD_TOWER */
    { "GUN", "Gun Turret" },             /* TXT_TURRET */
    { "HAND", "Hand of Nod" },           /* TXT_HAND */
    { "HARV", "Harvester" },             /* TXT_HARVESTER */
    { "HELI", "Attack Helicopter" },     /* TXT_HELI */
    { "HOSP", "Hospital" },              /* TXT_HOSPITAL */
    { "HPAD", "Helicopter Pad" },        /* TXT_HELIPAD */
    { "HQ", "Communications Center" },   /* TXT_COMMAND */
    { "HTNK", "Mammoth Tank" },          /* TXT_HTANK */
    { "JEEP", "Hum-vee" },               /* TXT_JEEP */
    { "LST", "Hovercraft" },             /* TXT_HOVER */
    { "LTNK", "Light Tank" },            /* TXT_LTANK */
    { "MCV", "Mobile Construction Yard" }, /* TXT_MCV */
    { "MHQ", "Mobile HQ" },              /* TXT_MHQ */
    { "MISS", "Technology Center" },     /* TXT_CIVMISS */
    { "MLRS", "S.S.M. Launcher" },       /* TXT_MSAM */
    { "MOEBIUS", "Dr. Moebius" },        /* TXT_MOEBIUS */
    { "MSAM", "Rocket Launcher" },       /* TXT_MLRS */
    { "MTNK", "Med. Tank" },             /* TXT_MTANK */
    { "NUK2", "Advanced Power Plant" },  /* TXT_ADVANCED_POWER */
    { "NUKE", "Power Plant" },           /* TXT_POWER */
    { "OBLI", "Obelisk Guard Tower" },   /* TXT_OBELISK */
    { "ORCA", "Orca" },                  /* TXT_ORCA */
    { "PROC", "Tiberium Refinery" },     /* TXT_REFINERY */
    { "PYLE", "Barracks" },              /* TXT_BARRACKS */
    { "RAPT", "Velociraptor" },          /* TXT_RAPT */
    { "RMBO", "Commando" },              /* TXT_RAMBO */
    { "ROAD", "Road" },                  /* TXT_ROAD */
    { "SAM", "SAM Site" },               /* TXT_SAM */
    { "SBAG", "Sandbag Wall" },          /* TXT_SANDBAG_WALL */
    { "SILO", "Tiberium Silo" },         /* TXT_STORAGE */
    { "STEG", "Stegasaurus" },           /* TXT_STEG */
    { "STNK", "Stealth Tank" },          /* TXT_STANK */
    { "TMPL", "Temple of Nod" },         /* TXT_TEMPLE */
    { "TRAN", "Transport Helicopter" },  /* TXT_TRANS */
    { "TREX", "Tyrannosaurus Rex" },     /* TXT_TREX */
    { "TRIC", "Triceratops" },           /* TXT_TRIC */
    { "V01", "Church" },                 /* TXT_CIV1 */
    { "V02", "Han's and Gretel's" },     /* TXT_CIV2 */
    { "V03", "Hewitt's Manor" },         /* TXT_CIV3 */
    { "V04", "Ricktor's House" },        /* TXT_CIV4 */
    { "V05", "Gretchin's House" },       /* TXT_CIV5 */
    { "V06", "The Barn" },               /* TXT_CIV6 */
    { "V07", "Damon's pub" },            /* TXT_CIV7 */
    { "V08", "Fran's House" },           /* TXT_CIV8 */
    { "V09", "Music Factory" },          /* TXT_CIV9 */
    { "V10", "Toymaker's" },             /* TXT_CIV10 */
    { "V11", "Ludwig's House" },         /* TXT_CIV11 */
    { "V12", "Haystacks" },              /* TXT_CIV12 */
    { "V13", "Haystack" },               /* TXT_CIV13 */
    { "V14", "Wheat Field" },            /* TXT_CIV14 */
    { "V15", "Fallow Field" },           /* TXT_CIV15 */
    { "V16", "Corn Field" },             /* TXT_CIV16 */
    { "V17", "Celery Field" },           /* TXT_CIV17 */
    { "V18", "Potato Field" },           /* TXT_CIV18 */
    { "V19", "Oil Pump" },               /* TXT_PUMP */
    { "V20", "Sala's House" },           /* TXT_CIV20 */
    { "V21", "Abdul's House" },          /* TXT_CIV21 */
    { "V22", "Pablo's Wicked Pub" },     /* TXT_CIV22 */
    { "V23", "Village Well" },           /* TXT_CIV23 */
    { "V24", "Camel Trader" },           /* TXT_CIV24 */
    { "V25", "Church" },                 /* TXT_CIV25 */
    { "V26", "Ali's House" },            /* TXT_CIV26 */
    { "V27", "Trader Ted's" },           /* TXT_CIV27 */
    { "V28", "Menelik's House" },        /* TXT_CIV28 */
    { "V29", "Prestor John's House" },   /* TXT_CIV29 */
    { "V30", "Village Well" },           /* TXT_CIV30 */
    { "V31", "Witch Doctor's Hut" },     /* TXT_CIV31 */
    { "V32", "Rikitikitembo's Hut" },    /* TXT_CIV32 */
    { "V33", "Roarke's Hut" },           /* TXT_CIV33 */
    { "V34", "Mubasa's Hut" },           /* TXT_CIV34 */
    { "V35", "Aksum's Hut" },            /* TXT_CIV35 */
    { "V36", "Mambo's Hut" },            /* TXT_CIV36 */
    { "V37", "The Studio" },             /* TXT_CIV37 */
    { "VICE", "Visceroid" },             /* TXT_VISCEROID */
    { "WEAP", "Weapons Factory" },       /* TXT_WEAPON_FACTORY */
    { "WOOD", "Wood Fence" },            /* TXT_WOOD_WALL */
    { "SB_REPAIR", "Repair Structure" },   /* TXT_REPAIR, chrome */
    { "SB_SELL", "Sell Structure" },   /* TXT_SELL, chrome */
    { "SB_DEMOLISH", "Demolish Structure" },   /* TXT_DEMOLISH, chrome */
    { "SB_MAP", "Map" },   /* TXT_MAP, chrome */
    { "SB_OPTIONS", "Options" },   /* TXT_OPTIONS, chrome */
};
#define DOSNAMES_COUNT ((int)(sizeof(DOSNAMES)/sizeof(DOSNAMES[0])))

#endif
