/* ====================================================================================
 *  edit_tables.h -- GENERATED by tools/gen_edit_tables.py. Do not edit by hand.
 *
 *  The map editor's legality tables, lifted from EA's GPL Tiberian Dawn source:
 *  Ground[LAND_COUNT] (const.cpp) and TemplateTypeClass (cdata.cpp). The browser
 *  prototype read the same numbers out of editor_tables.json at runtime; cnc_eyes
 *  has no JSON parser and is not getting one, so they are baked in here instead.
 *
 *  A cell's LandType is NOT simply its template's Land. A template also carries an
 *  AltLand and a list of icons that earn it, which is how a cliff of LAND_ROCK has
 *  walkable LAND_CLEAR notches in it. Resolve through edit_land_of().
 * ==================================================================================== */

#ifndef EDIT_TABLES_H
#define EDIT_TABLES_H

enum EditLand {
    EDIT_LAND_CLEAR     = 0,
    EDIT_LAND_ROAD      = 1,
    EDIT_LAND_WATER     = 2,
    EDIT_LAND_ROCK      = 3,
    EDIT_LAND_WALL      = 4,
    EDIT_LAND_TIBERIUM  = 5,
    EDIT_LAND_BEACH     = 6,
    EDIT_LAND_COUNT   = 7
};

static const char* const EDIT_LAND_NAME[EDIT_LAND_COUNT] = {
    "CLEAR", "ROAD", "WATER", "ROCK", "WALL", "TIBERIUM", "BEACH"
};

/* Ground[].Build and a foot cost of zero meaning impassable (const.cpp:245). */
static const unsigned char EDIT_LAND_BUILD[EDIT_LAND_COUNT] = {
    1, 1, 0, 0, 0, 0, 0
};
static const unsigned char EDIT_LAND_PASS[EDIT_LAND_COUNT] = {
    1, 1, 0, 0, 0, 1, 1
};

#define EDIT_TEMPLATE_COUNT 216
#define EDIT_ALT_MAX        9

/* The template's INI name, which is also how the editor groups the terrain
   drawers: CLEAR/P are ground, W water, SH shore, RV/FALLS/FORD rivers, D roads,
   B/BR rock, BRIDGE bridges. Cliffs (S*) are deliberately not offered as paint --
   they are derived from elevation. */
struct EditTemplate {
    const char*   name;
    unsigned char land;      /* EditLand                                        */
    unsigned char altland;   /* EditLand for the icons in alt[]                 */
    unsigned char nalt;      /* how many of alt[] are used                      */
    unsigned char alt[EDIT_ALT_MAX];
    unsigned char w, h;      /* the template's size in cells                    */
};

static const EditTemplate EDIT_TEMPLATES[EDIT_TEMPLATE_COUNT] = {
    { "CLEAR1", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 0 */
    { "W1", EDIT_LAND_WATER, EDIT_LAND_WATER, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 1 */
    { "W2", EDIT_LAND_WATER, EDIT_LAND_WATER, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 2 */
    { "SH1", EDIT_LAND_WATER, EDIT_LAND_BEACH, 6, {0, 1, 2, 3, 4, 5, 0, 0, 0}, 3, 3 },  /* 3 */
    { "SH2", EDIT_LAND_ROCK, EDIT_LAND_BEACH, 3, {0, 1, 2, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 4 */
    { "SH3", EDIT_LAND_ROCK, EDIT_LAND_WATER, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 5 */
    { "SH4", EDIT_LAND_ROCK, EDIT_LAND_WATER, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 1 },  /* 6 */
    { "SH5", EDIT_LAND_WATER, EDIT_LAND_BEACH, 6, {0, 1, 2, 3, 4, 5, 0, 0, 0}, 3, 3 },  /* 7 */
    { "SH11", EDIT_LAND_WATER, EDIT_LAND_BEACH, 2, {0, 3, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 8 */
    { "SH12", EDIT_LAND_WATER, EDIT_LAND_BEACH, 2, {5, 8, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 9 */
    { "SH13", EDIT_LAND_WATER, EDIT_LAND_BEACH, 1, {6, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 10 */
    { "SH14", EDIT_LAND_ROCK, EDIT_LAND_BEACH, 2, {6, 7, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 11 */
    { "SH15", EDIT_LAND_ROCK, EDIT_LAND_BEACH, 2, {6, 8, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 12 */
    { "S01", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {2, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 13 */
    { "S02", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 14 */
    { "S03", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 15 */
    { "S04", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 16 */
    { "S05", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 17 */
    { "S06", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 18 */
    { "S07", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 19 */
    { "S08", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 20 */
    { "S09", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {3, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 21 */
    { "S10", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 22 */
    { "S11", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 23 */
    { "S12", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 24 */
    { "S13", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {5, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 25 */
    { "S14", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 3, {1, 2, 3, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 26 */
    { "S15", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 27 */
    { "S16", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 28 */
    { "S17", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 29 */
    { "S18", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 30 */
    { "S19", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 31 */
    { "S20", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {5, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 32 */
    { "S21", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 2 },  /* 33 */
    { "S22", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 1 },  /* 34 */
    { "S23", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {5, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 35 */
    { "S24", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 36 */
    { "S25", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 37 */
    { "S26", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 38 */
    { "S27", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 2, {2, 3, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 39 */
    { "S28", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 40 */
    { "S29", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 41 */
    { "S30", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 42 */
    { "S31", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 43 */
    { "S32", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 44 */
    { "S33", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 45 */
    { "S34", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 46 */
    { "S35", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 47 */
    { "S36", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 48 */
    { "S37", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 49 */
    { "S38", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 50 */
    { "SH32", EDIT_LAND_CLEAR, EDIT_LAND_WATER, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 51 */
    { "SH33", EDIT_LAND_CLEAR, EDIT_LAND_WATER, 1, {2, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 52 */
    { "SH20", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 1 },  /* 53 */
    { "SH21", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 1 },  /* 54 */
    { "SH22", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 6, 2 },  /* 55 */
    { "SH23", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 56 */
    { "BR1", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 57 */
    { "BR2", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 58 */
    { "BR3", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 59 */
    { "BR4", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 60 */
    { "BR5", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 61 */
    { "BR6", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 62 */
    { "BR7", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 63 */
    { "BR8", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 64 */
    { "BR9", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 65 */
    { "BR10", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 1 },  /* 66 */
    { "P01", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 67 */
    { "P02", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 68 */
    { "P03", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 69 */
    { "P04", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 70 */
    { "P05", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 71 */
    { "P06", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 6, 4 },  /* 72 */
    { "P07", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 2 },  /* 73 */
    { "P08", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 74 */
    { "SH16", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 75 */
    { "SH17", EDIT_LAND_WATER, EDIT_LAND_WATER, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 76 */
    { "SH18", EDIT_LAND_WATER, EDIT_LAND_WATER, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 77 */
    { "SH19", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 78 */
    { "P13", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 79 */
    { "P14", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 1 },  /* 80 */
    { "P15", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 2 },  /* 81 */
    { "B1", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 82 */
    { "B2", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 1 },  /* 83 */
    { "B3", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 1 },  /* 84 */
    { "B4", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 85 */
    { "B5", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 86 */
    { "B6", EDIT_LAND_ROCK, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 87 */
    { "SH6", EDIT_LAND_WATER, EDIT_LAND_BEACH, 6, {0, 1, 2, 3, 4, 5, 0, 0, 0}, 3, 3 },  /* 88 */
    { "SH7", EDIT_LAND_WATER, EDIT_LAND_BEACH, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 89 */
    { "SH8", EDIT_LAND_WATER, EDIT_LAND_BEACH, 8, {0, 1, 2, 3, 4, 5, 6, 7, 0}, 3, 3 },  /* 90 */
    { "SH9", EDIT_LAND_WATER, EDIT_LAND_BEACH, 8, {0, 1, 2, 3, 4, 5, 7, 8, 0}, 3, 3 },  /* 91 */
    { "SH10", EDIT_LAND_WATER, EDIT_LAND_BEACH, 1, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 92 */
    { "D01", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 93 */
    { "D02", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 94 */
    { "D03", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 2 },  /* 95 */
    { "D04", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 96 */
    { "D05", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 4 },  /* 97 */
    { "D06", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 98 */
    { "D07", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 99 */
    { "D08", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 100 */
    { "D09", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 101 */
    { "D10", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 2 },  /* 102 */
    { "D11", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 103 */
    { "D12", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 104 */
    { "D13", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 105 */
    { "D14", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 106 */
    { "D15", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 107 */
    { "D16", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 108 */
    { "D17", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 109 */
    { "D18", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 110 */
    { "D19", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 111 */
    { "D20", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 112 */
    { "D21", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 113 */
    { "D22", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 114 */
    { "D23", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 115 */
    { "D24", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 116 */
    { "D25", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 117 */
    { "D26", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 118 */
    { "D27", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 119 */
    { "D28", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 120 */
    { "D29", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 121 */
    { "D30", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 122 */
    { "D31", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 123 */
    { "D32", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 124 */
    { "D33", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 125 */
    { "D34", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 126 */
    { "D35", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 127 */
    { "D36", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 128 */
    { "D37", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 129 */
    { "D38", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 130 */
    { "D39", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 131 */
    { "D40", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 132 */
    { "D41", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 133 */
    { "D42", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 134 */
    { "D43", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 135 */
    { "RV01", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 5, 4 },  /* 136 */
    { "RV02", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 5, 3 },  /* 137 */
    { "RV03", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {7, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 4 },  /* 138 */
    { "RV04", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 4 },  /* 139 */
    { "RV05", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 140 */
    { "RV06", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 141 */
    { "RV07", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 142 */
    { "RV08", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 143 */
    { "RV09", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 144 */
    { "RV10", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 145 */
    { "RV11", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 146 */
    { "RV12", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 4 },  /* 147 */
    { "RV13", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 4 },  /* 148 */
    { "RV14", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 149 */
    { "RV15", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 150 */
    { "RV16", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 6, 4 },  /* 151 */
    { "RV17", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 6, 5 },  /* 152 */
    { "RV18", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 4 },  /* 153 */
    { "RV19", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 4 },  /* 154 */
    { "RV20", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 6, 8 },  /* 155 */
    { "RV21", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 5, 8 },  /* 156 */
    { "RV22", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 157 */
    { "RV23", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 158 */
    { "RV24", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 159 */
    { "RV25", EDIT_LAND_WATER, EDIT_LAND_ROCK, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 160 */
    { "FORD1", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 5, {2, 3, 4, 5, 8, 0, 0, 0, 0}, 3, 3 },  /* 161 */
    { "FORD2", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 6, {0, 1, 2, 4, 7, 8, 0, 0, 0}, 3, 3 },  /* 162 */
    { "FALLS1", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 163 */
    { "FALLS2", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 164 */
    { "BRIDGE1", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 6, {2, 3, 6, 9, 12, 13, 0, 0, 0}, 4, 4 },  /* 165 */
    { "BRIDGE1D", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 4, {2, 3, 12, 13, 0, 0, 0, 0, 0}, 4, 4 },  /* 166 */
    { "BRIDGE2", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 8, {0, 1, 6, 12, 18, 19, 23, 24, 0}, 5, 5 },  /* 167 */
    { "BRIDGE2D", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 6, {0, 1, 18, 19, 23, 24, 0, 0, 0}, 5, 5 },  /* 168 */
    { "BRIDGE3", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 9, {3, 4, 6, 9, 11, 14, 19, 24, 25}, 6, 5 },  /* 169 */
    { "BRIDGE3D", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 7, {3, 4, 6, 11, 19, 25, 25, 0, 0}, 6, 5 },  /* 170 */
    { "BRIDGE4", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 4, {1, 8, 15, 22, 0, 0, 0, 0, 0}, 6, 4 },  /* 171 */
    { "BRIDGE4D", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 2, {1, 22, 0, 0, 0, 0, 0, 0, 0}, 6, 4 },  /* 172 */
    { "SH24", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {5, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 173 */
    { "SH25", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {3, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 174 */
    { "SH26", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 175 */
    { "SH27", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 1 },  /* 176 */
    { "SH28", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 1 },  /* 177 */
    { "SH29", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 1, {7, 0, 0, 0, 0, 0, 0, 0, 0}, 6, 2 },  /* 178 */
    { "SH30", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 179 */
    { "SH31", EDIT_LAND_ROCK, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 180 */
    { "P16", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 2 },  /* 181 */
    { "P17", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 2 },  /* 182 */
    { "P18", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 183 */
    { "P19", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 184 */
    { "P20", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 185 */
    { "SH34", EDIT_LAND_CLEAR, EDIT_LAND_WATER, 3, {2, 5, 8, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 186 */
    { "SH35", EDIT_LAND_CLEAR, EDIT_LAND_WATER, 3, {0, 3, 6, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 187 */
    { "SH36", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 188 */
    { "SH37", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 189 */
    { "SH38", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 190 */
    { "SH39", EDIT_LAND_CLEAR, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 1 },  /* 191 */
    { "SH40", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 192 */
    { "SH41", EDIT_LAND_CLEAR, EDIT_LAND_WATER, 5, {0, 1, 3, 4, 6, 0, 0, 0, 0}, 3, 3 },  /* 193 */
    { "SH42", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 2 },  /* 194 */
    { "SH43", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 3 },  /* 195 */
    { "SH44", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 3 },  /* 196 */
    { "SH45", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1, 2 },  /* 197 */
    { "SH46", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 3, {0, 1, 3, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 198 */
    { "SH47", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 199 */
    { "SH48", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 200 */
    { "SH49", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 3 },  /* 201 */
    { "SH50", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {7, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 202 */
    { "SH51", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 203 */
    { "SH52", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 3 },  /* 204 */
    { "SH53", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 4, {0, 1, 2, 4, 0, 0, 0, 0, 0}, 4, 3 },  /* 205 */
    { "SH54", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 206 */
    { "SH55", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {2, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 207 */
    { "SH56", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 208 */
    { "SH57", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 3, 2 },  /* 209 */
    { "SH58", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 210 */
    { "SH59", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 211 */
    { "SH60", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 2, {3, 5, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 212 */
    { "SH61", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 1, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 2, 3 },  /* 213 */
    { "SH62", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 6, 1 },  /* 214 */
    { "SH63", EDIT_LAND_WATER, EDIT_LAND_CLEAR, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 4, 1 },  /* 215 */
};

/* The LandType of one cell, from the (template, icon) pair a .BIN records.
   255 is TEMPLATE_NONE, which every shipped map uses for plain ground. */
static inline int edit_land_of(int tmpl_id, int icon)
{
    if (tmpl_id == 255) return EDIT_LAND_CLEAR;
    if (tmpl_id < 0 || tmpl_id >= EDIT_TEMPLATE_COUNT) return EDIT_LAND_CLEAR;
    {
        const EditTemplate* t = &EDIT_TEMPLATES[tmpl_id];
        for (int i = 0; i < (int)t->nalt; i++)
            if ((int)t->alt[i] == icon) return (int)t->altland;
        return (int)t->land;
    }
}


/* ------------------------------------------------------------------------------
 *  The placeable catalog: every type the editor can put on a map, with the cells
 *  it really occupies. NOT a width and a height -- PROC is four cells inside a
 *  3x2 and FIX is a plus. Bibbed buildings carry their bib row, because
 *  Occupy_List(placement) prepends it and the engine checks against that.
 * ---------------------------------------------------------------------------- */

enum EditKind {
    EDIT_KIND_BUILDING  = 0,
    EDIT_KIND_UNIT      = 1,
    EDIT_KIND_INFANTRY  = 2,
    EDIT_KIND_TERRAIN   = 3,
    EDIT_KIND_WALL      = 4,
    EDIT_KIND_TIBERIUM  = 5,
    EDIT_KIND_SMUDGE    = 6,
    EDIT_KIND_COUNT   = 7
};

#define EDIT_CELL_MAX  12
#define EDIT_ITEM_N    148

struct EditItem {
    const char*    code;      /* the INI code, and the cameo's name            */
    const char*    name;      /* the game's own display name                   */
    unsigned char  kind;      /* EditKind                                      */
    unsigned short str;       /* full strength                                 */
    unsigned char  n;         /* how many of dx/dy are used                    */
    signed char    dx[EDIT_CELL_MAX], dy[EDIT_CELL_MAX];
};

static const EditItem EDIT_ITEMS[EDIT_ITEM_N] = {
    /* ---- BUILDING ---- */
    { "TMPL", "Temple of Nod", EDIT_KIND_BUILDING, 1000, 9, {0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0}, {1, 1, 1, 2, 2, 2, 3, 3, 3, 0, 0, 0} },
    { "EYE", "Advanced Com. Center", EDIT_KIND_BUILDING, 500, 5, {0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0} },
    { "WEAP", "Weapons Factory", EDIT_KIND_BUILDING, 500, 9, {0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0}, {1, 1, 1, 2, 2, 2, 3, 3, 3, 0, 0, 0} },
    { "GTWR", "Guard Tower", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ATWR", "Advanced Guard Tower", EDIT_KIND_BUILDING, 300, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "OBLI", "Obelisk Guard Tower", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "GUN", "Gun Turret", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "FACT", "Construction Yard", EDIT_KIND_BUILDING, 400, 9, {0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0}, {0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0} },
    { "PROC", "Tiberium Refinery", EDIT_KIND_BUILDING, 450, 10, {1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0}, {0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 0, 0} },
    { "SILO", "Tiberium Silo", EDIT_KIND_BUILDING, 150, 4, {0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "HPAD", "Helicopter Pad", EDIT_KIND_BUILDING, 400, 6, {0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0}, {0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0} },
    { "HQ", "Communications Center", EDIT_KIND_BUILDING, 500, 5, {0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0} },
    { "SAM", "SAM Site", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "AFLD", "Airstrip", EDIT_KIND_BUILDING, 500, 12, {0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3}, {0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2} },
    { "NUKE", "Power Plant", EDIT_KIND_BUILDING, 200, 5, {0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0} },
    { "NUK2", "Advanced Power Plant", EDIT_KIND_BUILDING, 300, 5, {0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0} },
    { "HOSP", "Hospital", EDIT_KIND_BUILDING, 200, 6, {0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0}, {0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0} },
    { "BIO", "Bio-Research Laboratory", EDIT_KIND_BUILDING, 300, 6, {0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0}, {0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0} },
    { "PYLE", "Barracks", EDIT_KIND_BUILDING, 400, 6, {0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0}, {0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0} },
    { "HAND", "Hand of Nod", EDIT_KIND_BUILDING, 400, 6, {0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0}, {1, 1, 2, 2, 3, 3, 0, 0, 0, 0, 0, 0} },
    { "ARCO", "Oil Tanker", EDIT_KIND_BUILDING, 100, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "FIX", "Repair Bay", EDIT_KIND_BUILDING, 400, 10, {1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0}, {0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 0, 0} },
    { "ROAD", "Road", EDIT_KIND_BUILDING, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V01", "Church", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V02", "Han's and Gretel's", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V03", "Hewitt's Manor", EDIT_KIND_BUILDING, 200, 3, {1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V04", "Ricktor's House", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V05", "Gretchin's House", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V06", "The Barn", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V07", "Damon's pub", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V08", "Fran's House", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V09", "Music Factory", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V10", "Toymaker's", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V11", "Ludwig's House", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V12", "Haystacks", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V13", "Haystack", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V14", "Wheat Field", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V15", "Fallow Field", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V16", "Corn Field", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V17", "Celery Field", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V18", "Potato Field", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V19", "Oil Pump", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V20", "Sala's House", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V21", "Abdul's House", EDIT_KIND_BUILDING, 200, 3, {0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V22", "Pablo's Wicked Pub", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V23", "Village Well", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V24", "Camel Trader", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V25", "Church", EDIT_KIND_BUILDING, 200, 3, {1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V26", "Ali's House", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V27", "Trader Ted's", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V28", "Menelik's House", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V29", "Prestor John's House", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V30", "Village Well", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V31", "Witch Doctor's Hut", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V32", "Rikitikitembo's Hut", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V33", "Roarke's Hut", EDIT_KIND_BUILDING, 200, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V34", "Mubasa's Hut", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V35", "Aksum's Hut", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V36", "Mambo's Hut", EDIT_KIND_BUILDING, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "V37", "The Studio", EDIT_KIND_BUILDING, 300, 6, {1, 2, 3, 1, 2, 3, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0} },
    { "MISS", "Technology Center", EDIT_KIND_BUILDING, 200, 9, {0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0}, {0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0} },
    /* ---- UNIT ---- */
    { "VICE", "Visceroid", EDIT_KIND_UNIT, 150, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "FTNK", "Flame Tank", EDIT_KIND_UNIT, 300, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "STNK", "Stealth Tank", EDIT_KIND_UNIT, 110, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "LTNK", "Light Tank", EDIT_KIND_UNIT, 300, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "MTNK", "Med. Tank", EDIT_KIND_UNIT, 400, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "HTNK", "Mammoth Tank", EDIT_KIND_UNIT, 600, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "MHQ", "Mobile HQ", EDIT_KIND_UNIT, 110, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "LST", "Hovercraft", EDIT_KIND_UNIT, 400, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "MLRS", "S.S.M. Launcher", EDIT_KIND_UNIT, 120, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ARTY", "Artillery", EDIT_KIND_UNIT, 75, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "HARV", "Harvester", EDIT_KIND_UNIT, 600, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "MCV", "Mobile Construction Yard", EDIT_KIND_UNIT, 600, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "JEEP", "Hum-vee", EDIT_KIND_UNIT, 150, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "BGGY", "Nod Buggy", EDIT_KIND_UNIT, 140, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "BIKE", "Recon Bike", EDIT_KIND_UNIT, 90, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "MSAM", "Rocket Launcher", EDIT_KIND_UNIT, 100, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "APC", "APC", EDIT_KIND_UNIT, 200, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "BOAT", "Gun Boat", EDIT_KIND_UNIT, 700, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "TRIC", "Triceratops", EDIT_KIND_UNIT, 700, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "TREX", "Tyrannosaurus Rex", EDIT_KIND_UNIT, 750, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "RAPT", "Velociraptor", EDIT_KIND_UNIT, 180, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "STEG", "Stegasaurus", EDIT_KIND_UNIT, 600, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    /* ---- INFANTRY ---- */
    { "E1", "Minigunner", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "E2", "Grenadier", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "E3", "Bazooka", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "E4", "Flamethrower", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "E5", "Chem-warrior", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "E6", "Engineer", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "RMBO", "Commando", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C1", "Joe", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C2", "Bill", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C3", "Shelly", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C4", "Maria", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C5", "Eydie", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C6", "Dave", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C7", "Phil", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C8", "Dwight", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C9", "Erik", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "C10", "Nikoomba", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "MOEBIUS", "Dr. Moebius", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "DELPHI", "Agent Delphi", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "CHAN", "Dr. Chan", EDIT_KIND_INFANTRY, 50, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    /* ---- TERRAIN ---- */
    { "ROCK1", "Rock", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ROCK2", "Rock", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ROCK3", "Rock", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ROCK4", "Rock", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ROCK5", "Rock", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ROCK6", "Rock", EDIT_KIND_TERRAIN, 800, 3, {0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "ROCK7", "Rock", EDIT_KIND_TERRAIN, 800, 4, {0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SPLIT2", "Blossom Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SPLIT3", "Blossom Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T01", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T02", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T03", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T04", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T05", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T06", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T07", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T08", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T09", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T10", "Tree", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T11", "Tree", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T12", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T13", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T14", "Tree", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T15", "Tree", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T16", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T17", "Tree", EDIT_KIND_TERRAIN, 800, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "T18", "Tree", EDIT_KIND_TERRAIN, 800, 1, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "TC01", "Tree", EDIT_KIND_TERRAIN, 800, 2, {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "TC02", "Tree", EDIT_KIND_TERRAIN, 800, 3, {1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "TC03", "Tree", EDIT_KIND_TERRAIN, 800, 4, {0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "TC04", "Tree", EDIT_KIND_TERRAIN, 800, 4, {0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "TC05", "Tree", EDIT_KIND_TERRAIN, 800, 6, {2, 0, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0}, {0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0} },
    /* ---- WALL ---- */
    { "SBAG", "Sandbag Wall", EDIT_KIND_WALL, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "CYCL", "Chain Link Fence", EDIT_KIND_WALL, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "BRIK", "Concrete Wall", EDIT_KIND_WALL, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "BARB", "Barbwire Fence", EDIT_KIND_WALL, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "WOOD", "Wood Fence", EDIT_KIND_WALL, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    /* ---- TIBERIUM ---- */
    { "TI1", "Tiberium", EDIT_KIND_TIBERIUM, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    /* ---- SMUDGE ---- */
    { "CR1", "Crater", EDIT_KIND_SMUDGE, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SC1", "Scorch Mark 1", EDIT_KIND_SMUDGE, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SC2", "Scorch Mark 2", EDIT_KIND_SMUDGE, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SC3", "Scorch Mark 3", EDIT_KIND_SMUDGE, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SC4", "Scorch Mark 4", EDIT_KIND_SMUDGE, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SC5", "Scorch Mark 5", EDIT_KIND_SMUDGE, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
    { "SC6", "Scorch Mark 6", EDIT_KIND_SMUDGE, 1, 1, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} },
};

/* Where each group starts in EDIT_ITEMS, and how many it has. */
static const int EDIT_KIND_FIRST[EDIT_KIND_COUNT] = { 0, 61, 83, 103, 135, 140, 141 };
static const int EDIT_KIND_N[EDIT_KIND_COUNT]     = { 61, 22, 20, 32, 5, 1, 7 };
static const char* const EDIT_KIND_NAME[EDIT_KIND_COUNT] = { "BUILDING", "UNIT", "INFANTRY", "TERRAIN", "WALL", "TIBERIUM", "SMUDGE" };


/* ------------------------------------------------------------------------------
 *  StructType, in the engine's own order (bdata.cpp, the Pointers table).
 *
 *  A `Built It` trigger stores one of these indices in its Data field, so an
 *  editor that shows the raw number shows nothing at all: SCB05EA's
 *  `cnst=Built It,Dstry Trig 'YYYY',6` is really "when Nod finishes a
 *  Construction Yard". Civilian structures follow the buildable ones and are
 *  legal Data values too, however unlikely.
 * ---------------------------------------------------------------------------- */

#define EDIT_STRUCT_N 61
static const char* const EDIT_STRUCT_CODE[EDIT_STRUCT_N] = {
    "WEAP", "GTWR", "ATWR", "OBLI", "HQ", "GUN", "FACT", "PROC",
    "SILO", "HPAD", "SAM", "AFLD", "NUKE", "NUK2", "HOSP", "PYLE",
    "ARCO", "FIX", "BIO", "HAND", "TMPL", "EYE", "MISS", "V01",
    "V02", "V03", "V04", "V05", "V06", "V07", "V08", "V09",
    "V10", "V11", "V12", "V13", "V14", "V15", "V16", "V17",
    "V18", "V19", "V20", "V21", "V22", "V23", "V24", "V25",
    "V26", "V27", "V28", "V29", "V30", "V31", "V32", "V33",
    "V34", "V35", "V36", "V37", "ROAD"
};

#endif /* EDIT_TABLES_H */
