/* GENERATED by game/gen_efx_recipes.py from tools/romdump/particle_recipes.json.
   DO NOT EDIT BY HAND -- re-run the generator. Every number below is the
   cartridge's own: anim table ROM 0x1B6444, source table ROM 0x1B41C0, visual
   sub-records ROM 0xA2C2C+. Units are WORLD UNITS, 256 to the cell (the JSON's
   _meta string says 192; it is wrong, see this file's generator header). */
#ifndef CNC3D_EFX_RECIPES_H
#define CNC3D_EFX_RECIPES_H

struct EfxSourceRec {
    const char*   name;         /* the ROM's own SOURCE_* string, minus prefix */
    unsigned char sys;          /* particle system index; see EFX_SYS          */
    unsigned char nvar;         /* visual variants (only Debris/Debris2 have 2)*/
    float ppt, mult;            /* +0x10 particles/tick, +0x14 multiplier      */
    short burst;                /* +0x18 ticks; 0 = continuous (re-armed)      */
    float spd, spdR;            /* +0x1C/+0x20 world units per tick            */
    short life, lifeR;          /* +0x24/+0x28 ticks                           */
    float size, sizeR;          /* +0x2C/+0x30 world units (a diameter)        */
    float aMin, aMax, bMin, bMax;   /* +0x34..+0x40 radians                    */
    float yacc, grow;           /* visual +0x20 accel.y, +0x2C size growth/tick*/
    unsigned char a, r, g, b;   /* visual +0x32..+0x35                         */
    unsigned char arate;        /* visual +0x31, the ALPHA RAMP SLOPE per tick  */
};

static const EfxSourceRec EFX_SRC[65] = {
  { "None", 0, 1, 6.000000f, 0.800000f, 5, 20.000000f, 5.000000f, 10, 5, 50.000000f, 0.000000f, -1.000000f, 0.000000f, -0.500000f, 0.500000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_N", 0, 1, 6.000000f, 0.800000f, 5, 10.600000f, 5.000000f, 10, 5, 70.599701f, 44.499901f, -1.000000f, 0.000000f, -0.500000f, 0.500000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_NE", 0, 1, 6.000000f, 0.800000f, 5, 10.600000f, 5.000000f, 10, 5, 70.599701f, 44.499901f, -1.000000f, 0.000000f, 0.000000f, 1.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_E", 0, 1, 6.000000f, 0.800000f, 5, 10.600000f, 5.000000f, 10, 5, 70.599701f, 44.499901f, -0.500000f, 0.500000f, 0.000000f, 1.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_SE", 0, 1, 6.000000f, 0.800000f, 5, 10.600000f, 5.000000f, 10, 5, 70.599701f, 44.499901f, 0.000000f, 1.000000f, 0.000000f, 1.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_S", 0, 1, 2.618999f, 0.800000f, 0, 10.600000f, 5.000000f, 10, 5, 24.768410f, 60.424427f, 0.000000f, 1.000000f, -0.500000f, 0.500000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_SW", 0, 1, 6.000000f, 0.800000f, 5, 10.600000f, 5.000000f, 10, 5, 70.599701f, 44.499901f, 0.000000f, 1.000000f, -1.000000f, 0.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_W", 0, 1, 6.000000f, 0.800000f, 5, 10.600000f, 5.000000f, 10, 5, 70.599701f, 44.499901f, -0.500000f, 0.500000f, -1.000000f, 0.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Sam_NW", 0, 1, 6.000000f, 0.800000f, 5, 10.600000f, 5.000000f, 10, 5, 70.599701f, 44.499901f, -1.000000f, 0.000000f, -1.000000f, 0.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_N", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 10, 5, 30.599701f, 0.000000f, -1.000000f, 0.000000f, -0.500000f, 0.500000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_NE", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 10, 5, 30.000000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f, 1.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_E", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 2, 5, 30.000000f, 0.000000f, -0.500000f, 0.500000f, 0.000000f, 1.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_SE", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 2, 5, 30.000000f, 0.000000f, 0.000000f, 1.000000f, 0.000000f, 1.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_S", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 2, 5, 30.000000f, 0.000000f, 0.000000f, 1.000000f, -0.500000f, 0.500000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_SW", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 2, 5, 30.000000f, 0.000000f, 0.000000f, 1.000000f, -1.000000f, 0.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_W", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 2, 5, 30.000000f, 0.000000f, -0.500000f, 0.500000f, -1.000000f, 0.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Gun_NW", 0, 1, 6.000000f, 0.800000f, 2, 5.000000f, 4.000000f, 2, 5, 30.000000f, 0.000000f, -1.000000f, 0.000000f, -1.000000f, 0.000000f, 0.400000f, 0.000000f, 255, 150, 150, 150, 0x10 },
  { "Flame_N", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, -2.000000f, -0.010000f, 0.010000f, 0.000000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Flame_NE", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, -1.010000f, -0.990000f, 0.990000f, 1.010000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Flame_E", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, -0.010000f, 0.010000f, 0.990000f, 1.010000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Flame_SE", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, 0.990000f, 1.010000f, 0.990000f, 1.010000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Flame_S", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, 0.990000f, 1.010000f, -0.010000f, 0.010000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Flame_SW", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, 0.990000f, 1.010000f, -1.010000f, -0.990000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Flame_W", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, -0.010000f, 0.010000f, -1.010000f, -0.990000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Flame_NW", 9, 1, 1.071499f, 176.768173f, 0, 11.974000f, 5.000000f, 15, 5, 32.000000f, 8.000000f, -1.010000f, -0.990000f, -1.010000f, -0.990000f, 0.400000f, 2.000000f, 255, 255, 127, 102, 0x10 },
  { "Debris", 2, 2, 5.000000f, 0.600000f, 4, 20.000000f, 5.000000f, 40, 10, 0.250000f, 0.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, -2.000000f, -0.005000f, 255, 197, 106, 0, 0x10 },
  { "Debris2", 3, 2, 10.000000f, 0.600000f, 4, 20.000000f, 5.000000f, 40, 10, 0.250000f, 0.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, -2.000000f, -0.005000f, 255, 197, 106, 0, 0x10 },
  { "Sparks", 0, 1, 10.500000f, 0.800000f, 1, 10.000000f, 5.000000f, 7, 3, 13.500000f, 5.900000f, -1.000000f, 1.000000f, -1.000000f, 1.000000f, 0.400000f, 0.100000f, 78, 43, 202, 255, 0x10 },
  { "Dirt", 0, 1, 7.100000f, 0.800000f, 4, 20.000099f, 9.100000f, 6, 3, 20.000000f, 6.600000f, -1.000000f, 1.000000f, -1.000000f, 1.000000f, 0.400000f, 2.000000f, 255, 255, 70, 0, 0x10 },
  { "Shock", 4, 1, 1.000000f, 0.000000f, 1, 10.000000f, 5.000000f, 10, 5, 65.399498f, 10.000000f, 0.000000f, 0.500000f, -0.500000f, 0.500000f, 0.400000f, 14.200000f, 164, 255, 255, 255, 0x10 },
  { "Burn_Fire", 5, 1, 1.200000f, 1.020000f, 0, 3.000000f, 5.000000f, 10, 5, 7.826155f, -2.079650f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.819999f, 8.799997f, 136, 255, 255, 255, 0x32 },
  { "Burn_Smoke", 6, 1, 1.600000f, 1.040000f, 20, 12.500000f, 3.400000f, 10, 5, 39.199902f, 3.400000f, -0.650000f, 0.400000f, -0.400000f, 0.350000f, 2.010000f, 15.700024f, 140, 255, 255, 255, 0x10 },
  { "Ion_Spark", 7, 1, 20.400000f, 1.140000f, 0, 49.999802f, 80.699303f, 10, 5, 30.000000f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 0.400000f, 2.000000f, 255, 0, 0, 0, 0x10 },
  { "Burn_L", 5, 1, 6.000000f, 0.800000f, 0, 10.000000f, 5.000000f, 10, 1, 30.000000f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.819999f, 8.799997f, 136, 255, 255, 255, 0x32 },
  { "Burn_M", 5, 1, 4.698749f, 0.800000f, 0, 10.000000f, 1.354750f, 10, 1, 5.292253f, 0.369751f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.819999f, 6.070767f, 136, 255, 255, 255, 0x32 },
  { "Burn_S", 5, 1, 2.402000f, 0.800000f, 0, 10.000000f, 5.000000f, 8, 0, 14.231250f, 5.232500f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.819999f, 3.537393f, 136, 255, 255, 255, 0x32 },
  { "Flame_Spout", 5, 1, 1.950000f, 0.800000f, 0, 18.604752f, 0.861751f, 10, 5, 26.721251f, 7.282501f, -0.003000f, 0.006000f, -0.001000f, -0.001000f, 1.525850f, 2.000000f, 255, 255, 173, 213, 0x30 },
  { "Napalm_S", 5, 1, 1.665000f, 1.020000f, 0, 3.000000f, 5.000000f, 10, 5, 2.627425f, 1.737100f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.109990f, 20.500000f, 136, 255, 255, 255, 0x10 },
  { "Napalm_M", 5, 1, 2.200000f, 1.020000f, 0, 3.000000f, 5.000000f, 10, 5, 6.113922f, 6.595850f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.109990f, 20.500000f, 136, 255, 255, 255, 0x10 },
  { "Napalm_L", 5, 1, 2.400000f, 1.020000f, 0, 3.000000f, 5.000000f, 10, 5, 74.099403f, 30.300100f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.109990f, 20.500000f, 136, 255, 255, 255, 0x10 },
  { "Fire_S", 5, 1, 2.232200f, 0.800000f, 0, 4.499996f, 5.000000f, 10, 5, 30.000000f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 0.300000f, 5.099998f, 136, 255, 255, 255, 0x20 },
  { "Fire_M", 5, 1, 2.170000f, 0.040000f, 0, 8.999996f, 1.480000f, 10, 2, 30.000000f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 0.860000f, 5.999997f, 136, 255, 255, 255, 0x32 },
  { "Fire_L", 5, 1, 1.925749f, 0.100000f, 0, 4.008001f, 1.763999f, 20, 0, 24.088249f, 2.482251f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 1.819999f, 5.429595f, 136, 255, 255, 255, 0x32 },
  { "Smoke_L", 6, 1, 1.600000f, 1.100000f, 0, 12.500000f, 3.400000f, 10, 5, 14.699945f, 3.400000f, -0.650000f, 0.400000f, -0.400000f, 0.350000f, 2.010000f, 15.700024f, 140, 255, 255, 255, 0x10 },
  { "Smoke_M", 6, 1, 1.600000f, 1.100000f, 0, 12.500000f, 3.400000f, 10, 5, 9.399925f, 3.400000f, -0.650000f, 0.400000f, -0.400000f, 0.350000f, 2.010000f, 15.700024f, 140, 255, 255, 255, 0x10 },
  { "Smokey", 6, 1, 1.600000f, 1.100000f, 0, 12.500000f, 3.400000f, 10, 5, 2.299920f, 3.400000f, -0.650000f, 0.400000f, -0.400000f, 0.350000f, 2.010000f, 15.700024f, 140, 255, 255, 255, 0x10 },
  { "Smoke_Burn_L", 6, 1, 1.600000f, 1.100000f, 0, 37.545757f, 3.400000f, 10, 5, 165.517227f, 3.400000f, -0.065000f, 0.040000f, -0.110000f, 0.170000f, 2.010000f, 21.000044f, 140, 255, 255, 255, 0x10 },
  { "Smoke_Burn_M", 6, 1, 1.600000f, 1.100000f, 0, 12.500000f, 3.400000f, 10, 5, 9.399925f, 3.400000f, -0.650000f, 0.400000f, -0.400000f, 0.350000f, 0.400000f, 20.300039f, 182, 255, 255, 255, 0x10 },
  { "Smoke_Burn_S", 6, 1, 1.600000f, 1.100000f, 0, 12.500000f, 3.400000f, 10, 5, 2.299920f, 3.400000f, -0.650000f, 0.400000f, -0.400000f, 0.350000f, 0.400000f, 10.000020f, 182, 255, 255, 255, 0x10 },
  { "Smoke_Spout", 6, 1, 1.875749f, 0.800000f, 0, 9.270507f, 5.000000f, 10, 5, 57.735996f, 10.000000f, -0.112725f, 0.198125f, -0.197225f, 0.218250f, 0.400000f, 2.000000f, 255, 0, 0, 0, 0x10 },
  { "Napalm_Smoke_S", 6, 1, 1.600000f, 1.040000f, 0, 12.500000f, 3.400000f, 10, 5, 39.199902f, 3.400000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 2.009999f, 26.300640f, 140, 255, 255, 255, 0x10 },
  { "Napalm_Smoke_M", 6, 1, 1.600000f, 1.040000f, 0, 12.500000f, 3.400000f, 10, 5, 39.199902f, 3.400000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 2.009999f, 26.300640f, 140, 255, 255, 255, 0x10 },
  { "Napalm_Smoke_L", 6, 1, 1.600000f, 1.040000f, 0, 12.500000f, 3.400000f, 10, 5, 189.376862f, 3.400000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 2.009999f, 26.300640f, 140, 255, 255, 255, 0x10 },
  { "Explode_S", 1, 1, 2.000004f, 1.010000f, 3, 10.000000f, 5.000000f, 10, 5, 30.000000f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 0.400000f, 8.899998f, 209, 255, 199, 101, 0x10 },
  { "Explode_M", 1, 1, 2.000004f, 1.010000f, 3, 10.000000f, 5.000000f, 10, 5, 30.000000f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 0.400000f, 24.500057f, 209, 255, 199, 101, 0x10 },
  { "Explode_L", 1, 1, 2.000004f, 1.240000f, 3, 26.300062f, 5.000000f, 10, 5, 30.600002f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 0.400000f, 30.000076f, 209, 255, 255, 255, 0x10 },
  { "Explode_Debris", 6, 1, 6.000000f, 0.800000f, 2, 10.000000f, 5.000000f, 10, 5, 30.000000f, 10.000000f, -0.500000f, 0.500000f, -0.500000f, 0.500000f, 0.400000f, 2.000000f, 255, 0, 0, 0, 0x10 },
  { "Lightning_1", 7, 1, 9.200003f, 1.699999f, 6, 5.400000f, 5.000000f, 16, 5, 24.499979f, 10.000000f, -1.049999f, 1.459999f, -0.450000f, 0.430000f, 2.159980f, 2.000000f, 255, 255, 255, 255, 0x04 },
  { "Lightning_2", 7, 1, 9.200003f, 1.699999f, 6, 5.400000f, 5.000000f, 16, 5, 24.499979f, 10.000000f, -1.049999f, 1.459999f, -0.450000f, 0.430000f, 2.159980f, 2.000000f, 255, 255, 255, 255, 0x04 },
  { "Lightning_3", 7, 1, 9.200003f, 1.699999f, 6, 5.400000f, 5.000000f, 16, 5, 24.499979f, 10.000000f, -1.049999f, 1.459999f, -0.450000f, 0.430000f, 2.159980f, 2.000000f, 255, 255, 255, 255, 0x04 },
  { "Lightning_4", 7, 1, 9.200003f, 1.699999f, 6, 5.400000f, 5.000000f, 16, 5, 24.499979f, 10.000000f, -1.049999f, 1.459999f, -0.450000f, 0.430000f, 2.159980f, 2.000000f, 255, 255, 255, 255, 0x04 },
  { "Lightning_5", 7, 1, 9.200003f, 1.699999f, 6, 5.400000f, 5.000000f, 16, 5, 24.499979f, 10.000000f, -1.049999f, 1.459999f, -0.450000f, 0.430000f, 2.159980f, 2.000000f, 255, 255, 255, 255, 0x04 },
  { "Lightning_6", 7, 1, 9.200003f, 1.699999f, 6, 5.400000f, 5.000000f, 16, 5, 24.499979f, 10.000000f, -1.049999f, 1.459999f, -0.450000f, 0.430000f, 2.159980f, 2.000000f, 255, 255, 255, 255, 0x04 },
  { "Lightning_7", 7, 1, 9.200003f, 1.699999f, 6, 5.400000f, 5.000000f, 16, 5, 24.499979f, 10.000000f, -1.049999f, 1.459999f, -0.450000f, 0.430000f, 2.159980f, 2.000000f, 255, 255, 255, 255, 0x04 },
  { "LandingSmoke", 1, 1, 2.755750f, 0.800000f, 0, 10.700000f, 1.456001f, 16, 3, 64.869507f, 10.000000f, -0.200000f, 0.500000f, -0.010000f, -0.610000f, 1.940000f, 3.373189f, 255, 60, 193, 2, 0x21 },
};

/* `arate` is the visual sub-record's byte +0x31, and it is the ALPHA RAMP SLOPE.

   This used to be read as "texture frames per tick in 1/64ths" -- a hypothesis that
   fitted the table's shape and some reference frames, and was wrong. The ROM settles
   both halves of it:

     FRAME. Both draw paths compute the frame from age and life and nothing else:
       RAM 0x80050060 (triangle) and RAM 0x80050298 (quad) do
         lbu a0,0x39 (life total); lbu v0,0x30 (life left); lw v1,0x28(sys) (nframes);
         subu; mult; div  ->  frame = (total - left) * nframes / total
       applied as a T offset of frame * 32 texels down a vertical film strip
       (RAM 0x800500F8..0x8005011C). The whole strip is stretched across the life.

     ALPHA. RAM 0x8004FFC8 does
         lbu a0,0x30 (life left); lbu v0,0x31; mult; lbu v1,0x32; slt
       i.e. alpha = min(lifeLeft * byte31, byte32), written to the vertex at
       RAM 0x80050138. byte32 is the CAP (the value we already store as `a`), and
       byte31 is the slope: full alpha until lifeLeft * slope falls under the cap,
       then a linear fade to nothing. The action integrator at RAM 0x8004F300/0x8004F314
       copies both bytes out of the visual record.

   Values are unchanged, only their meaning: Burn_Fire family 0x32 = 50,
   Explode_* / Debris and most others 0x10 = 16, Lightning 0x04 = 4, Flame_Spout 0x30,
   Fire_S 0x20, LandingSmoke 0x21. */

/* SOURCE_Debris / _Debris2 declare TWO visual variants: identical physics
   (y accel -2.0 per tick^2, elasticity 0.70) with colour 255,255,255 instead of
   the burnt orange of variant 0. Both are on screen in the reference frames
   (p080: dark-red chunks AND white-grey chunks leaving the same blast). */
static const unsigned char EFX_DEBRIS_VAR1[4] = { 255, 255, 255, 255 };
static const float EFX_CHUNK_YACC   = -2.000000f;   /* world units per tick^2 */
static const float EFX_CHUNK_BOUNCE = 0.700000f;   /* visual +0x28 elasticity */
/* The chunk's size step, visual sub-record +0x2C at ROM 0xA2C58, integrated at
   RAM 0x8004EF90. 0.25 / 0.005 is exactly 50 ticks against a 40..50 tick life, so a
   chunk dwindles to nothing as it dies rather than popping out at full size. */
static const float EFX_CHUNK_SHRINK = -0.005000f;

/* One slot = one emitter the anim instantiates. dx/dz are world-unit offsets
   from the anim's own cell; dy is added to the TERRAIN HEIGHT under (x,z), not
   to the anim's y (spawn wrapper RAM 0x801FC918 calls the ground-height fn and
   adds dy to its result). A slot fires when the anim's stage reaches its
   fire_stage: burst sources exactly once, continuous sources every stage. */
struct EfxSlot { unsigned char src, stage; short dx, dy, dz; };
struct EfxRecipe { const char* name; unsigned char nslot; EfxSlot slot[10]; };

static const EfxRecipe EFX_RECIPE[66] = {
  { "FBALL1", 0, { } },
  { "GRENADE", 2, { {28,2,0,0,0}, {53,0,0,0,0}, } },
  { "FRAG1", 4, { {25,0,0,0,0}, {40,0,0,0,0}, {5,0,0,0,0}, {55,0,0,0,0}, } },
  { "FRAG2", 4, { {25,0,0,0,0}, {30,0,0,0,0}, {31,1,0,0,0}, {54,0,0,0,0}, } },
  { "FRAG3", 4, { {26,0,0,0,0}, {30,0,0,0,0}, {31,1,0,0,0}, {54,0,0,0,0}, } },
  { "VEH_HIT1", 3, { {53,0,0,0,0}, {28,0,0,0,0}, {27,0,0,0,0}, } },
  { "VEH_HIT2", 3, { {28,0,0,0,0}, {54,0,0,0,0}, {1,2,0,-10,0}, } },
  { "VEH_HIT3", 2, { {54,0,0,0,0}, {28,0,0,0,0}, } },
  { "ART_EXP1", 4, { {54,0,0,0,0}, {1,3,0,52,-67}, {28,0,0,0,0}, {53,2,56,163,169}, } },
  { "NAPALM1", 2, { {37,0,0,0,0}, {50,1,-8,165,-23}, } },
  { "NAPALM2", 2, { {38,0,0,0,0}, {51,1,-8,165,-58}, } },
  { "NAPALM3", 2, { {39,0,0,0,0}, {52,1,-8,165,-207}, } },
  { "SMOKE_PUFF", 1, { {5,0,0,0,0}, } },
  { "PIFF", 1, { {11,0,0,0,0}, } },
  { "PIFFPIFF", 2, { {11,0,0,0,0}, {12,0,0,0,0}, } },
  { "FLAME_N", 1, { {17,0,0,0,0}, } },
  { "FLAME_NE", 1, { {18,0,0,0,0}, } },
  { "FLAME_E", 1, { {19,0,0,0,0}, } },
  { "FLAME_SE", 1, { {20,0,0,0,0}, } },
  { "FLAME_S", 1, { {21,0,0,0,0}, } },
  { "FLAME_SW", 1, { {22,0,0,0,0}, } },
  { "FLAME_W", 1, { {23,0,0,0,0}, } },
  { "FLAME_NW", 1, { {24,0,0,0,0}, } },
  { "FIRE_SMALL", 2, { {40,0,0,0,0}, {44,0,0,0,0}, } },
  { "FIRE_MED", 2, { {41,0,0,0,0}, {44,0,0,0,0}, } },
  { "FIRE_MED2", 3, { {41,0,0,0,0}, {47,0,0,0,0}, {31,0,0,0,0}, } },
  { "FIRE_TINY", 2, { {40,0,0,0,0}, {48,0,0,0,0}, } },
  { "MUZZLE_FLASH", 0, { } },
  { "SMOKE_M", 0, { } },
  { "BURN_SMALL", 2, { {40,0,0,0,0}, {48,0,0,0,0}, } },
  { "BURN_MED", 2, { {41,0,0,0,0}, {47,0,0,0,0}, } },
  { "BURN_BIG", 4, { {42,0,0,0,0}, {46,3,0,152,0}, {30,0,0,0,0}, {31,0,0,0,0}, } },
  { "ON_FIRE_SMALL", 2, { {40,0,0,0,0}, {48,0,0,0,0}, } },
  { "ON_FIRE_MED", 2, { {41,0,0,0,0}, {47,0,0,0,0}, } },
  { "ON_FIRE_BIG", 2, { {42,0,0,0,0}, {46,0,0,0,0}, } },
  { "SAM_N", 1, { {1,0,0,0,0}, } },
  { "SAM_NE", 1, { {2,0,0,0,0}, } },
  { "SAM_E", 1, { {3,0,0,0,0}, } },
  { "SAM_SE", 1, { {4,0,0,0,0}, } },
  { "SAM_S", 1, { {5,0,0,0,0}, } },
  { "SAM_SW", 1, { {6,0,0,0,0}, } },
  { "SAM_W", 1, { {7,0,0,0,0}, } },
  { "SAM_NW", 1, { {8,0,0,0,0}, } },
  { "GUN_N", 1, { {9,0,0,0,0}, } },
  { "GUN_NE", 1, { {10,0,0,0,0}, } },
  { "GUN_E", 1, { {11,0,0,0,0}, } },
  { "GUN_SE", 1, { {12,0,0,0,0}, } },
  { "GUN_S", 1, { {13,0,0,0,0}, } },
  { "GUN_SW", 1, { {14,0,0,0,0}, } },
  { "GUN_W", 1, { {15,0,0,0,0}, } },
  { "GUN_NW", 1, { {16,0,0,0,0}, } },
  { "LZ_SMOKE", 2, { {64,0,0,0,0}, {28,0,0,0,0}, } },
  { "ION_CANNON", 0, { } },
  { "ATOM_BLAST", 7, { {42,0,548,0,279}, {42,3,-357,0,423}, {42,5,365,0,-234}, {42,2,-208,0,-345}, {42,1,245,0,455}, {42,8,-254,0,567}, {42,9,346,0,356}, } },
  { "CRATE_DEVIATOR", 0, { } },
  { "CRATE_DOLLAR", 0, { } },
  { "CRATE_EARTH", 0, { } },
  { "CRATE_EMPULSE", 0, { } },
  { "CRATE_INVUN", 0, { } },
  { "CRATE_MINE", 0, { } },
  { "CRATE_RAPID", 0, { } },
  { "CRATE_STEALTH", 0, { } },
  { "CRATE_MISSILE", 0, { } },
  { "ATOM_DOOR", 0, { } },
  { "MOVE_FLASH", 0, { } },
  { "OILFIELD_BURN", 0, { } },
};

/* 16 of the 66 cartridge anims have every slot empty. That is a DECISION in the
   ROM, not a gap in the decode: the spawn wrapper skips a zero source_id
   (RAM 0x801FC884) and there is no fallback source anywhere in it. They are:
   FBALL1, MUZZLE_FLASH, SMOKE_M, ION_CANNON, CRATE_DEVIATOR, CRATE_DOLLAR, CRATE_EARTH, CRATE_EMPULSE, CRATE_INVUN, CRATE_MINE, CRATE_RAPID, CRATE_STEALTH, CRATE_MISSILE, ATOM_DOOR, MOVE_FLASH, OILFIELD_BURN. */

/* The engine's AnimType -> the cartridge's anim-table index. NOT the identity:
   the N64 enum gained ANIM_FRAG3 (its index 4) and dropped the eight
   ANIM_CHEM_*, so everything after ANIM_FRAG2 is shifted by +1 and then by -7.
   -1 means the cartridge has no such anim at all; an EMPTY recipe (nslot 0) is
   a different thing entirely -- there the console deliberately spawns nothing.
   INDEX THIS WITH `type=`, NEVER WITH THE ART NAME. */
static const signed char EFX_ANIM2RECIPE[85] = {
    0, /*  0 ANIM_FBALL1 */
    1, /*  1 ANIM_GRENADE */
    2, /*  2 ANIM_FRAG1 */
    3, /*  3 ANIM_FRAG2 */
    5, /*  4 ANIM_VEH_HIT1 */
    6, /*  5 ANIM_VEH_HIT2 */
    7, /*  6 ANIM_VEH_HIT3 */
    8, /*  7 ANIM_ART_EXP1 */
    9, /*  8 ANIM_NAPALM1 */
   10, /*  9 ANIM_NAPALM2 */
   11, /* 10 ANIM_NAPALM3 */
   12, /* 11 ANIM_SMOKE_PUFF */
   13, /* 12 ANIM_PIFF */
   14, /* 13 ANIM_PIFFPIFF */
   15, /* 14 ANIM_FLAME_N */
   16, /* 15 ANIM_FLAME_NE */
   17, /* 16 ANIM_FLAME_E */
   18, /* 17 ANIM_FLAME_SE */
   19, /* 18 ANIM_FLAME_S */
   20, /* 19 ANIM_FLAME_SW */
   21, /* 20 ANIM_FLAME_W */
   22, /* 21 ANIM_FLAME_NW */
   -1, /* 22 ANIM_CHEM_N   -- no N64 counterpart */
   -1, /* 23 ANIM_CHEM_NE   -- no N64 counterpart */
   -1, /* 24 ANIM_CHEM_E   -- no N64 counterpart */
   -1, /* 25 ANIM_CHEM_SE   -- no N64 counterpart */
   -1, /* 26 ANIM_CHEM_S   -- no N64 counterpart */
   -1, /* 27 ANIM_CHEM_SW   -- no N64 counterpart */
   -1, /* 28 ANIM_CHEM_W   -- no N64 counterpart */
   -1, /* 29 ANIM_CHEM_NW   -- no N64 counterpart */
   23, /* 30 ANIM_FIRE_SMALL */
   24, /* 31 ANIM_FIRE_MED */
   25, /* 32 ANIM_FIRE_MED2 */
   26, /* 33 ANIM_FIRE_TINY */
   27, /* 34 ANIM_MUZZLE_FLASH */
   28, /* 35 ANIM_SMOKE_M */
   29, /* 36 ANIM_BURN_SMALL */
   30, /* 37 ANIM_BURN_MED */
   31, /* 38 ANIM_BURN_BIG */
   32, /* 39 ANIM_ON_FIRE_SMALL */
   33, /* 40 ANIM_ON_FIRE_MED */
   34, /* 41 ANIM_ON_FIRE_BIG */
   35, /* 42 ANIM_SAM_N */
   36, /* 43 ANIM_SAM_NE */
   37, /* 44 ANIM_SAM_E */
   38, /* 45 ANIM_SAM_SE */
   39, /* 46 ANIM_SAM_S */
   40, /* 47 ANIM_SAM_SW */
   41, /* 48 ANIM_SAM_W */
   42, /* 49 ANIM_SAM_NW */
   43, /* 50 ANIM_GUN_N */
   44, /* 51 ANIM_GUN_NE */
   45, /* 52 ANIM_GUN_E */
   46, /* 53 ANIM_GUN_SE */
   47, /* 54 ANIM_GUN_S */
   48, /* 55 ANIM_GUN_SW */
   49, /* 56 ANIM_GUN_W */
   50, /* 57 ANIM_GUN_NW */
   51, /* 58 ANIM_LZ_SMOKE */
   52, /* 59 ANIM_ION_CANNON */
   53, /* 60 ANIM_ATOM_BLAST */
   54, /* 61 ANIM_CRATE_DEVIATOR */
   55, /* 62 ANIM_CRATE_DOLLAR */
   56, /* 63 ANIM_CRATE_EARTH */
   57, /* 64 ANIM_CRATE_EMPULSE */
   58, /* 65 ANIM_CRATE_INVUN */
   59, /* 66 ANIM_CRATE_MINE */
   60, /* 67 ANIM_CRATE_RAPID */
   61, /* 68 ANIM_CRATE_STEALTH */
   62, /* 69 ANIM_CRATE_MISSILE */
   63, /* 70 ANIM_ATOM_DOOR */
   64, /* 71 ANIM_MOVE_FLASH */
   65, /* 72 ANIM_OILFIELD_BURN */
   -1, /* 73 ANIM_TRIC_DIE   -- no N64 counterpart */
   -1, /* 74 ANIM_TREX_DIE   -- no N64 counterpart */
   -1, /* 75 ANIM_STEG_DIE   -- no N64 counterpart */
   -1, /* 76 ANIM_RAPT_DIE   -- no N64 counterpart */
   -1, /* 77 ANIM_CHEM_BALL   -- no N64 counterpart */
   -1, /* 78 ANIM_FLAG   -- no N64 counterpart */
   -1, /* 79 ANIM_BEACON   -- no N64 counterpart */
   -1, /* 80 ANIM_FIRE_SMALL_VIRTUAL   -- no N64 counterpart */
   -1, /* 81 ANIM_FIRE_MED_VIRTUAL   -- no N64 counterpart */
   -1, /* 82 ANIM_FIRE_MED2_VIRTUAL   -- no N64 counterpart */
   -1, /* 83 ANIM_FIRE_TINY_VIRTUAL   -- no N64 counterpart */
   -1, /* 84 ANIM_BEACON_VIRTUAL   -- no N64 counterpart */
};
static const int EFX_ANIM2RECIPE_N = 85;

#endif /* CNC3D_EFX_RECIPES_H */
