/* ====================================================================================
 *  fx_panel.h -- the F5 tuning panel.
 *
 *  Press F5 in game. Toggles and sliders for every dial in FX_PARAMS, live, on a
 *  moving picture. SAVE writes the current values to a text file; that file is what
 *  gets sent back, and its numbers become the new defaults in fx_state.h.
 *
 *  IT LISTS NOTHING. Every control on it is generated by walking FX_PARAMS, so a dial
 *  cannot exist in the chain and be missing from the panel, and the panel cannot show
 *  a dial that does nothing. That is the same reason the save file and the loader walk
 *  the same table: four hand-maintained copies of one list is how a fix to one of them
 *  outlives its own correction.
 *
 *  WHY A PANEL AND NOT MORE KEYBOARD SHORTCUTS. This renderer already tunes shadows
 *  and effect sizes with bracket keys, and that convention stops working at sixty
 *  parameters. The judgement being made here is an ART judgement -- someone looking at a
 *  moving battlefield and deciding -- so the instrument has to show every number at
 *  once so one dial can be dragged while another is watched.
 *
 *  SELF CONTAINED ON PURPOSE. Its own 5x7 font, its own texture, its own quads. It
 *  does NOT borrow the DOS sidebar's font printer, because a debug instrument that
 *  stops working when a pack fails to load is an instrument you cannot use to
 *  diagnose a pack that failed to load.
 *
 *  Tier 2 only, like everything it drives. It is also drawn AFTER fx_present, on the
 *  real framebuffer, so it is never bloomed, graded, scanlined or supersampled: the
 *  panel must read the same however the dials are set.
 * ==================================================================================== */
#ifndef CNC3D_FX_PANEL_H
#define CNC3D_FX_PANEL_H

#include "fx_state.h"
#include "fx_filter.h"

/* ---- A 5x7 font, five column bytes per glyph, bit 0 at the top ------------------- */
static const unsigned char FXP_FONT[95][5] = {
{0x00,0x00,0x00,0x00,0x00},{0x00,0x00,0x5F,0x00,0x00},{0x00,0x07,0x00,0x07,0x00},
{0x14,0x7F,0x14,0x7F,0x14},{0x24,0x2A,0x7F,0x2A,0x12},{0x23,0x13,0x08,0x64,0x62},
{0x36,0x49,0x55,0x22,0x50},{0x00,0x05,0x03,0x00,0x00},{0x00,0x1C,0x22,0x41,0x00},
{0x00,0x41,0x22,0x1C,0x00},{0x14,0x08,0x3E,0x08,0x14},{0x08,0x08,0x3E,0x08,0x08},
{0x00,0x50,0x30,0x00,0x00},{0x08,0x08,0x08,0x08,0x08},{0x00,0x60,0x60,0x00,0x00},
{0x20,0x10,0x08,0x04,0x02},{0x3E,0x51,0x49,0x45,0x3E},{0x00,0x42,0x7F,0x40,0x00},
{0x42,0x61,0x51,0x49,0x46},{0x21,0x41,0x45,0x4B,0x31},{0x18,0x14,0x12,0x7F,0x10},
{0x27,0x45,0x45,0x45,0x39},{0x3C,0x4A,0x49,0x49,0x30},{0x01,0x71,0x09,0x05,0x03},
{0x36,0x49,0x49,0x49,0x36},{0x06,0x49,0x49,0x29,0x1E},{0x00,0x36,0x36,0x00,0x00},
{0x00,0x56,0x36,0x00,0x00},{0x08,0x14,0x22,0x41,0x00},{0x14,0x14,0x14,0x14,0x14},
{0x00,0x41,0x22,0x14,0x08},{0x02,0x01,0x51,0x09,0x06},{0x32,0x49,0x79,0x41,0x3E},
{0x7E,0x11,0x11,0x11,0x7E},{0x7F,0x49,0x49,0x49,0x36},{0x3E,0x41,0x41,0x41,0x22},
{0x7F,0x41,0x41,0x22,0x1C},{0x7F,0x49,0x49,0x49,0x41},{0x7F,0x09,0x09,0x09,0x01},
{0x3E,0x41,0x49,0x49,0x7A},{0x7F,0x08,0x08,0x08,0x7F},{0x00,0x41,0x7F,0x41,0x00},
{0x20,0x40,0x41,0x3F,0x01},{0x7F,0x08,0x14,0x22,0x41},{0x7F,0x40,0x40,0x40,0x40},
{0x7F,0x02,0x0C,0x02,0x7F},{0x7F,0x04,0x08,0x10,0x7F},{0x3E,0x41,0x41,0x41,0x3E},
{0x7F,0x09,0x09,0x09,0x06},{0x3E,0x41,0x51,0x21,0x5E},{0x7F,0x09,0x19,0x29,0x46},
{0x46,0x49,0x49,0x49,0x31},{0x01,0x01,0x7F,0x01,0x01},{0x3F,0x40,0x40,0x40,0x3F},
{0x1F,0x20,0x40,0x20,0x1F},{0x3F,0x40,0x38,0x40,0x3F},{0x63,0x14,0x08,0x14,0x63},
{0x07,0x08,0x70,0x08,0x07},{0x61,0x51,0x49,0x45,0x43},{0x00,0x7F,0x41,0x41,0x00},
{0x02,0x04,0x08,0x10,0x20},{0x00,0x41,0x41,0x7F,0x00},{0x04,0x02,0x01,0x02,0x04},
{0x40,0x40,0x40,0x40,0x40},{0x00,0x01,0x02,0x04,0x00},{0x20,0x54,0x54,0x54,0x78},
{0x7F,0x48,0x44,0x44,0x38},{0x38,0x44,0x44,0x44,0x20},{0x38,0x44,0x44,0x48,0x7F},
{0x38,0x54,0x54,0x54,0x18},{0x08,0x7E,0x09,0x01,0x02},{0x0C,0x52,0x52,0x52,0x3E},
{0x7F,0x08,0x04,0x04,0x78},{0x00,0x44,0x7D,0x40,0x00},{0x20,0x40,0x44,0x3D,0x00},
{0x7F,0x10,0x28,0x44,0x00},{0x00,0x41,0x7F,0x40,0x00},{0x7C,0x04,0x18,0x04,0x78},
{0x7C,0x08,0x04,0x04,0x78},{0x38,0x44,0x44,0x44,0x38},{0x7C,0x14,0x14,0x14,0x08},
{0x08,0x14,0x14,0x18,0x7C},{0x7C,0x08,0x04,0x04,0x08},{0x48,0x54,0x54,0x54,0x20},
{0x04,0x3F,0x44,0x40,0x20},{0x3C,0x40,0x40,0x20,0x7C},{0x1C,0x20,0x40,0x20,0x1C},
{0x3C,0x40,0x30,0x40,0x3C},{0x44,0x28,0x10,0x28,0x44},{0x0C,0x50,0x50,0x50,0x3C},
{0x44,0x64,0x54,0x4C,0x44},{0x00,0x08,0x36,0x41,0x00},{0x00,0x00,0x7F,0x00,0x00},
{0x00,0x41,0x36,0x08,0x00},{0x08,0x08,0x2A,0x1C,0x08}
};

#define FXP_CELLW 6
#define FXP_CELLH 8
#define FXP_COLS  16
#define FXP_ROWS  6

static GLuint g_fxpFont = 0;

/* One 96x48 atlas, built once, drawn one quad per character. The obvious alternative
   -- a quad per lit PIXEL -- is 35 quads a glyph and tens of thousands a frame for a
   panel this size, which is a real cost for an instrument that is meant to be left
   open while judging a moving picture. */
static void fxp_font_init(void)
{
    if (g_fxpFont) return;
    const int W = FXP_COLS * FXP_CELLW, H = FXP_ROWS * FXP_CELLH;
    unsigned char* px = (unsigned char*)calloc((size_t)W * H * 4, 1);
    if (!px) return;
    for (int g = 0; g < 95; g++) {
        const int gx = (g % FXP_COLS) * FXP_CELLW;
        const int gy = (g / FXP_COLS) * FXP_CELLH;
        for (int c = 0; c < 5; c++) {
            const unsigned char col = FXP_FONT[g][c];
            for (int r = 0; r < 7; r++) {
                if (!(col & (1 << r))) continue;
                unsigned char* o = px + (((size_t)(gy + r) * W) + (gx + c)) * 4;
                o[0] = o[1] = o[2] = o[3] = 255;
            }
        }
    }
    glGenTextures(1, &g_fxpFont);
    glBindTexture(GL_TEXTURE_2D, g_fxpFont);
    /* NEAREST, and deliberately NOT registered with fx_filter: the panel has to read
       the same whatever the bilinear toggle it is carrying is set to. */
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, W, H, 0, GL_RGBA, GL_UNSIGNED_BYTE, px);
    free(px);
}

/* ---- Panel state ------------------------------------------------------------------ */

static int   g_fxpOpen   = 0;
static int   g_fxpScroll = 0;
static int   g_fxpDrag   = -1;      /* index into FX_PARAMS being dragged, or -1 */
static char  g_fxpStatus[192] = "F5 closes. Drag a slider, then SAVE.";
static char  g_fxpSavePath[512] = "cnc3d-fx.cfg";

/* Geometry, all in unscaled units; everything is multiplied by an integer scale so the
   panel stays legible on a 5K window without ever landing on a half pixel. */
#define FXP_W      348
#define FXP_ROWH    15
#define FXP_TOP     64
#define FXP_LABX     8
#define FXP_TRKX   176
#define FXP_TRKW   112
#define FXP_VALX   292

static int fxp_scale(int fbh) { int s = fbh / 620; if (s < 1) s = 1; if (s > 3) s = 3; return s; }

static void fxp_set_save_path(const char* p)
{
    if (!p || !*p) return;
    snprintf(g_fxpSavePath, sizeof g_fxpSavePath, "%s", p);
}

static int fxp_is_open(void) { return g_fxpOpen; }

/* Is this screen column inside the panel? Asked by update_cursor for exactly the reason
   it asks sb_over_panel the same question: over an instrument the pointer is a plain
   arrow, not an attack reticle aimed at whatever the panel happens to be covering. It
   also clears g_cursorOnMap, which stops the world cursor being drawn on the ground
   under the panel and stops the pick running at all. */
static int fxp_over_panel(float col, int fbh)
{
    if (!g_fxpOpen) return 0;
    return col >= 0.0f && col < (float)(FXP_W * fxp_scale(fbh));
}

/* NO GL HERE. This is reachable from argv parsing, which on the shipping binary runs
   before the window exists, and the font atlas is built lazily by fxp_draw for exactly
   that reason: a toggle that uploaded a texture would segfault on --gfxpanel. */
static void fxp_toggle(void)
{
    g_fxpOpen = !g_fxpOpen;
    g_fxpDrag = -1;
    fprintf(stderr, "FX|panel|%s\n", g_fxpOpen ? "open" : "closed");
}

/* Anything that changes a value goes through here, so the one setting with a side
   effect outside the shader uniforms cannot be changed without its side effect. */
static void fxp_after_change(const FxParam* p)
{
    if (p && !strcmp(p->key, "bilinear"))
        fx_filter_set(g_fx.bilinear);
    if (p && !strcmp(p->key, "texset"))
        fx_texset_set((int)g_fx.texset);
    if (p && !strcmp(p->key, "infset"))
        fx_infset_set((int)g_fx.infset);
}

static void fxp_apply_all_side_effects(void)
{
    fx_filter_set(g_fx.bilinear);
    fx_texset_set((int)g_fx.texset);
    fx_infset_set((int)g_fx.infset);
}

/* ---- Row layout -------------------------------------------------------------------
   Walked twice: once to hit-test, once to draw. Same function, so a control can never
   be drawn somewhere it cannot be clicked. */
typedef void (*FxpRowFn)(const FxParam* p, int idx, int y, void* ctx);

static int fxp_walk(int fbh, int scale, FxpRowFn fn, void* ctx)
{
    int y = FXP_TOP - g_fxpScroll;
    int i = 0;
    for (const FxParam* p = FX_PARAMS; p->kind != FXP_END; p++, i++) {
        const int h = (p->kind == FXP_GROUP) ? FXP_ROWH + 7 : FXP_ROWH;
        if (fn && y * scale < fbh && (y + h) > 0)
            fn(p, i, y, ctx);
        y += h;
    }
    return y + g_fxpScroll - FXP_TOP;      /* total content height, unscrolled */
}

/* ---- Hit testing ------------------------------------------------------------------ */

struct FxpHit { int mx, my; int idx; int onTrack; };

static void fxp_hit_row(const FxParam* p, int idx, int y, void* ctx)
{
    FxpHit* h = (FxpHit*)ctx;
    if (p->kind == FXP_GROUP) return;
    if (h->my < y || h->my >= y + FXP_ROWH) return;
    h->idx = idx;
    h->onTrack = (p->kind != FXP_BOOL && h->mx >= FXP_TRKX && h->mx <= FXP_TRKX + FXP_TRKW);
}

static void fxp_set_from_x(const FxParam* p, int mx)
{
    float t = (float)(mx - FXP_TRKX) / (float)FXP_TRKW;
    t = fx_clampf(t, 0.0f, 1.0f);
    *fx_fptr(&g_fx, p) = fx_quant(p, p->lo + t * (p->hi - p->lo));
}

/* ---- Buttons ---------------------------------------------------------------------- */

/* x, w, and what they do. Kept as a table for the same reason FX_PARAMS is one. */
enum { FXPB_SAVE = 0, FXPB_DEFAULTS, FXPB_ALLOFF, FXPB_N };
static const struct { int x, w; const char* label; } FXP_BTN[FXPB_N] = {
    {   8, 74, "SAVE"     },
    {  88, 106, "DEFAULTS" },
    { 200, 96, "ALL OFF"  },
};

static void fxp_button(int which)
{
    switch (which) {
    case FXPB_SAVE:
        if (fx_save(&g_fx, g_fxpSavePath)) {
            snprintf(g_fxpStatus, sizeof g_fxpStatus, "saved: %s", g_fxpSavePath);
            fprintf(stderr, "FX|saved|%s\n", g_fxpSavePath);
        } else {
            snprintf(g_fxpStatus, sizeof g_fxpStatus, "COULD NOT WRITE %s", g_fxpSavePath);
            fprintf(stderr, "FX|save FAILED|%s\n", g_fxpSavePath);
        }
        break;
    case FXPB_DEFAULTS: {
        const int wasOn = g_fx.enabled, wasBi = g_fx.bilinear;
        fx_defaults(&g_fx);
        /* Keep the two master switches where they were: somebody pressing DEFAULTS
           wants the numbers back, not the picture switched off underneath them. */
        g_fx.enabled = wasOn; g_fx.bilinear = wasBi;
        fxp_apply_all_side_effects();
        snprintf(g_fxpStatus, sizeof g_fxpStatus, "values reset to the shipped defaults");
        break;
    }
    case FXPB_ALLOFF:
        g_fx.enabled = 0;
        g_fx.bilinear = 0;
        fxp_apply_all_side_effects();
        snprintf(g_fxpStatus, sizeof g_fxpStatus, "everything off: the shipped picture");
        break;
    }
}

/* ---- Events -----------------------------------------------------------------------
   Returns 1 when the panel took the event. The caller MUST honour that: a click that
   lands on a slider must not also order a tank across the map behind it. */
static int fxp_event(const SDL_Event* e, int fbw, int fbh, float mscaleX, float mscaleY)
{
    if (e->type == SDL_KEYDOWN && e->key.keysym.sym == SDLK_F5) { fxp_toggle(); return 1; }
    if (!g_fxpOpen) return 0;

    const int scale = fxp_scale(fbh);
    const int panelW = FXP_W * scale;
    (void)fbw;

    if (e->type == SDL_KEYDOWN && e->key.keysym.sym == SDLK_ESCAPE) {
        g_fxpOpen = 0; g_fxpDrag = -1; return 1;
    }

    if (e->type == SDL_MOUSEWHEEL) {
        int mx = 0, my = 0;
        SDL_GetMouseState(&mx, &my);
        if ((int)(mx * mscaleX) >= panelW) return 0;
        g_fxpScroll -= e->wheel.y * 3 * FXP_ROWH;
        const int content = fxp_walk(fbh, scale, NULL, NULL);
        const int maxs = content - (fbh / scale - FXP_TOP) + FXP_ROWH * 2;
        if (g_fxpScroll > maxs) g_fxpScroll = maxs > 0 ? maxs : 0;
        if (g_fxpScroll < 0) g_fxpScroll = 0;
        return 1;
    }

    if (e->type == SDL_MOUSEBUTTONUP && e->button.button == SDL_BUTTON_LEFT) {
        if (g_fxpDrag >= 0) { g_fxpDrag = -1; return 1; }
        return 0;
    }

    if (e->type == SDL_MOUSEMOTION) {
        if (g_fxpDrag >= 0) {
            const int mx = (int)(e->motion.x * mscaleX) / scale;
            fxp_set_from_x(&FX_PARAMS[g_fxpDrag], mx);
            fxp_after_change(&FX_PARAMS[g_fxpDrag]);
        }
        /* MOTION IS NEVER CONSUMED, not even over the panel and not even mid-drag, and
           that is a fix rather than an oversight. Swallowing it froze the game's own
           pointer position, and the pointer is what DRAWS the cursor: update_cursor runs
           once a frame off g_mouseScrC/R, so with those stuck at the last on-map
           position it went on believing the pointer was over the battlefield, where the
           3D world cursor draws instead of the sprite -- and the world cursor is under
           the panel. The panel had no cursor on it at all (reported, first fullscreen run
           with F5 open).

           Letting motion through is also the self-consistent answer rather than a
           workaround: update_cursor already asks fxp_over_panel and forces the plain
           arrow there, exactly as it does for the sidebar, so the game handles a pointer
           over the panel correctly the moment it is told about one. Buttons are still
           consumed -- a click on a slider must never also order a tank. */
        return 0;
    }

    if (e->type == SDL_MOUSEBUTTONDOWN && e->button.button == SDL_BUTTON_LEFT) {
        const int fx_ = (int)(e->button.x * mscaleX);
        const int fy_ = (int)(e->button.y * mscaleY);
        if (fx_ >= panelW) return 0;
        const int mx = fx_ / scale, my = fy_ / scale;

        /* the button strip */
        if (my >= 34 && my < 34 + 18) {
            for (int b = 0; b < FXPB_N; b++)
                if (mx >= FXP_BTN[b].x && mx < FXP_BTN[b].x + FXP_BTN[b].w) {
                    fxp_button(b);
                    return 1;
                }
            return 1;
        }

        FxpHit h; h.mx = mx; h.my = my; h.idx = -1; h.onTrack = 0;
        fxp_walk(fbh, scale, fxp_hit_row, &h);
        if (h.idx < 0) return 1;               /* inside the panel, on nothing */
        const FxParam* p = &FX_PARAMS[h.idx];
        if (p->kind == FXP_BOOL) {
            int* v = fx_iptr(&g_fx, p);
            *v = !*v;
            fxp_after_change(p);
        } else if (h.onTrack) {
            fxp_set_from_x(p, mx);
            fxp_after_change(p);
            g_fxpDrag = h.idx;
        }
        return 1;
    }

    /* Everything else that happens over the panel is swallowed, so the world does not
       see a stray click, drag or keystroke aimed at an instrument. */
    if (e->type == SDL_MOUSEBUTTONDOWN || e->type == SDL_MOUSEBUTTONUP) {
        int mx = 0, my = 0;
        SDL_GetMouseState(&mx, &my);
        return ((int)(mx * mscaleX) < panelW) ? 1 : 0;
    }
    return 0;
}

/* ---- Drawing ---------------------------------------------------------------------- */

static void fxp_rect(float x, float y, float w, float h,
                     float r, float g, float b, float a)
{
    glDisable(GL_TEXTURE_2D);
    glColor4f(r, g, b, a);
    glBegin(GL_QUADS);
    glVertex2f(x, y); glVertex2f(x + w, y);
    glVertex2f(x + w, y + h); glVertex2f(x, y + h);
    glEnd();
}

static void fxp_text(float x, float y, const char* s, float sc,
                     float r, float g, float b, float a)
{
    if (!g_fxpFont || !s) return;
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, g_fxpFont);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
    glColor4f(r, g, b, a);
    const float TW = (float)(FXP_COLS * FXP_CELLW), TH = (float)(FXP_ROWS * FXP_CELLH);
    glBegin(GL_QUADS);
    float px = x;
    for (const unsigned char* c = (const unsigned char*)s; *c; c++) {
        if (*c == ' ') { px += 6.0f * sc; continue; }
        if (*c < 32 || *c > 126) { px += 6.0f * sc; continue; }
        const int gi = *c - 32;
        const float u0 = (float)((gi % FXP_COLS) * FXP_CELLW) / TW;
        const float v0 = (float)((gi / FXP_COLS) * FXP_CELLH) / TH;
        const float u1 = u0 + (float)FXP_CELLW / TW;
        const float v1 = v0 + (float)FXP_CELLH / TH;
        const float w = FXP_CELLW * sc, hh = FXP_CELLH * sc;
        glTexCoord2f(u0, v0); glVertex2f(px, y);
        glTexCoord2f(u1, v0); glVertex2f(px + w, y);
        glTexCoord2f(u1, v1); glVertex2f(px + w, y + hh);
        glTexCoord2f(u0, v1); glVertex2f(px, y + hh);
        px += 6.0f * sc;
    }
    glEnd();
    glDisable(GL_TEXTURE_2D);
}

struct FxpDraw { float sc; int fbh; };

static void fxp_draw_row(const FxParam* p, int idx, int y, void* ctx)
{
    FxpDraw* d = (FxpDraw*)ctx;
    const float sc = d->sc;
    (void)idx;

    if (p->kind == FXP_GROUP) {
        fxp_rect(0.0f, (y + 12) * sc, FXP_W * sc, 1.0f * sc, 0.35f, 0.55f, 0.35f, 0.85f);
        fxp_text(FXP_LABX * sc, (y + 3) * sc, p->label, sc, 0.62f, 0.95f, 0.62f, 1.0f);
        return;
    }

    const int on = (p->kind == FXP_BOOL) ? *(const int*)((const char*)&g_fx + p->off) : 1;
    fxp_text(FXP_LABX * sc, (y + 3) * sc, p->label, sc,
             on ? 0.90f : 0.55f, on ? 0.90f : 0.55f, on ? 0.90f : 0.55f, 1.0f);

    if (p->kind == FXP_BOOL) {
        const float bx = FXP_TRKX * sc, by = (y + 2) * sc, bs = 10.0f * sc;
        fxp_rect(bx, by, bs, bs, 0.10f, 0.10f, 0.12f, 1.0f);
        fxp_rect(bx, by, bs, 1.0f * sc, 0.55f, 0.60f, 0.55f, 1.0f);
        fxp_rect(bx, by + bs - sc, bs, 1.0f * sc, 0.55f, 0.60f, 0.55f, 1.0f);
        fxp_rect(bx, by, 1.0f * sc, bs, 0.55f, 0.60f, 0.55f, 1.0f);
        fxp_rect(bx + bs - sc, by, 1.0f * sc, bs, 0.55f, 0.60f, 0.55f, 1.0f);
        if (on)
            fxp_rect(bx + 2 * sc, by + 2 * sc, bs - 4 * sc, bs - 4 * sc,
                     0.35f, 0.95f, 0.40f, 1.0f);
        fxp_text(FXP_VALX * sc, (y + 3) * sc, on ? "ON" : "off", sc,
                 on ? 0.45f : 0.50f, on ? 0.95f : 0.50f, on ? 0.50f : 0.50f, 1.0f);
        return;
    }

    const float v = *(const float*)((const char*)&g_fx + p->off);
    float t = (p->hi > p->lo) ? (v - p->lo) / (p->hi - p->lo) : 0.0f;
    t = fx_clampf(t, 0.0f, 1.0f);

    fxp_rect(FXP_TRKX * sc, (y + 6) * sc, FXP_TRKW * sc, 2.0f * sc,
             0.22f, 0.24f, 0.26f, 1.0f);
    fxp_rect(FXP_TRKX * sc, (y + 6) * sc, FXP_TRKW * t * sc, 2.0f * sc,
             0.35f, 0.70f, 0.90f, 1.0f);
    fxp_rect((FXP_TRKX + FXP_TRKW * t - 2) * sc, (y + 2) * sc, 4.0f * sc, 10.0f * sc,
             0.80f, 0.88f, 0.95f, 1.0f);

    char buf[32];
    if (p->step >= 1.0f)      snprintf(buf, sizeof buf, "%.0f", v);
    else if (p->step > 0.0f)  snprintf(buf, sizeof buf, "%.2f", v);
    else if (p->hi <= 0.05f)  snprintf(buf, sizeof buf, "%.4f", v);
    else                      snprintf(buf, sizeof buf, "%.3f", v);
    fxp_text(FXP_VALX * sc, (y + 3) * sc, buf, sc, 0.80f, 0.85f, 0.90f, 1.0f);
}

static void fxp_draw(int fbw, int fbh)
{
    if (!g_fxpOpen) return;
    fxp_font_init();

    const int scale = fxp_scale(fbh);
    const float sc = (float)scale;

    glMatrixMode(GL_PROJECTION); glPushMatrix(); glLoadIdentity();
    glOrtho(0.0, (double)fbw, (double)fbh, 0.0, -1.0, 1.0);
    glMatrixMode(GL_MODELVIEW);  glPushMatrix(); glLoadIdentity();

    glDisable(GL_DEPTH_TEST);
    glDepthMask(GL_FALSE);
    glDisable(GL_ALPHA_TEST);
    glDisable(GL_CULL_FACE);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    glActiveTexture(GL_TEXTURE0);

    /* the plate */
    fxp_rect(0.0f, 0.0f, FXP_W * sc, (float)fbh, 0.05f, 0.06f, 0.07f, 0.90f);
    fxp_rect(FXP_W * sc, 0.0f, 1.0f * sc, (float)fbh, 0.30f, 0.55f, 0.35f, 0.9f);

    /* title, state, buttons */
    fxp_text(FXP_LABX * sc, 6 * sc, "CNC3D  TIER 2  PRESENTATION", sc,
             0.60f, 0.95f, 0.65f, 1.0f);
    {
        char head[96];
        snprintf(head, sizeof head, "%s   %s",
                 g_fxUsable ? "shaders ok" : "SHADERS UNAVAILABLE",
                 g_fx.enabled ? "chain ON" : "chain off");
        fxp_text(FXP_LABX * sc, 18 * sc, head, sc,
                 g_fxUsable ? 0.60f : 1.0f, g_fxUsable ? 0.70f : 0.45f, 0.70f, 1.0f);
    }
    for (int b = 0; b < FXPB_N; b++) {
        fxp_rect(FXP_BTN[b].x * sc, 34 * sc, FXP_BTN[b].w * sc, 16 * sc,
                 0.16f, 0.20f, 0.24f, 1.0f);
        fxp_rect(FXP_BTN[b].x * sc, 34 * sc, FXP_BTN[b].w * sc, 1.0f * sc,
                 0.45f, 0.55f, 0.60f, 1.0f);
        fxp_text((FXP_BTN[b].x + 8) * sc, 38 * sc, FXP_BTN[b].label, sc,
                 0.85f, 0.92f, 0.95f, 1.0f);
    }

    FxpDraw d; d.sc = sc; d.fbh = fbh;
    fxp_walk(fbh, scale, fxp_draw_row, &d);

    /* the status strip, pinned to the bottom so a long list cannot scroll it away */
    fxp_rect(0.0f, (float)fbh - 14 * sc, FXP_W * sc, 14 * sc, 0.10f, 0.12f, 0.14f, 0.96f);
    fxp_text(FXP_LABX * sc, (float)fbh - 11 * sc, g_fxpStatus, sc,
             0.75f, 0.85f, 0.75f, 1.0f);

    glDisable(GL_BLEND);
    glColor4f(1.0f, 1.0f, 1.0f, 1.0f);
    glEnable(GL_DEPTH_TEST);
    glDepthMask(GL_TRUE);
    glMatrixMode(GL_PROJECTION); glPopMatrix();
    glMatrixMode(GL_MODELVIEW);  glPopMatrix();
}

#endif /* CNC3D_FX_PANEL_H */
