#!/usr/bin/env python3
"""
gen_efx_recipes.py -- turn tools/romdump/particle_recipes.json into game/efx_recipes.h.

Nothing in the output is hand-typed: every number comes from the JSON, which was itself
read straight out of data/rom/cnc_eu.z64 (anim table CodeOverlay ROM 0x1B6444, source
table ROM 0x1B41C0, visual sub-records ROM 0xA2C2C+). Re-run whenever the JSON is
re-derived:

    cd game && python3 gen_efx_recipes.py > efx_recipes.h

The one thing this script contributes that the JSON does not is the DOS AnimType ->
N64 anim-table-index map. The cartridge's own AnimType enum is NOT the DOS one (it
gained ANIM_FRAG3 and dropped the eight ANIM_CHEM_*), so the renderer cannot index the
table with the engine's `type` field directly -- and it must index with `type`, not the
art NAME, because the names are ambiguous: "VEH-HIT2" is the IniName of BOTH
ANIM_GRENADE (adata.cpp:798) and ANIM_VEH_HIT2 (adata.cpp:912), whose recipes differ
completely, and the four FIRE names are scrambled against the enum.

A NOTE ON UNITS. particle_recipes.json's _meta says "cell = 192" world units in two
places. That string is WRONG and the renderer must not use it: a cell is 256 world
units (tools/romdump/heightmap_notes.md:12 and :69 -- vtx.x = x*256, vtx.y = h*4 --
and docs/n64-camera-math.md, which puts cell (cx,cy) at (cx*256, 0, cy*256)). No
NUMBER in the JSON depends on the string; only the divisor in effects_mod.h does, and
that is EFX_U = 1/256.
"""
import json
import os
import sys

# ---------------------------------------------------------------- DOS AnimType
# tiberiandawn/defines.h:1404 (the #ifdef NEVER E*_ROT block does NOT compile in).
# Verified against a live run of SCG01EC: EFXDUMP shows FRAG1 type=2, SMOKEY type=11
# (= ANIM_SMOKE_PUFF, the missile trail puff), PIFF type=12, FIRE3 type=30
# (ANIM_FIRE_SMALL), GUNFIRE type=34 (ANIM_MUZZLE_FLASH), SMOKE_M type=35, and
# FIRE3 type=80 (ANIM_FIRE_SMALL_VIRTUAL) sharing a cell with the type=30 one.
DOS = """FBALL1 GRENADE FRAG1 FRAG2 VEH_HIT1 VEH_HIT2 VEH_HIT3 ART_EXP1 NAPALM1
NAPALM2 NAPALM3 SMOKE_PUFF PIFF PIFFPIFF FLAME_N FLAME_NE FLAME_E FLAME_SE FLAME_S
FLAME_SW FLAME_W FLAME_NW CHEM_N CHEM_NE CHEM_E CHEM_SE CHEM_S CHEM_SW CHEM_W
CHEM_NW FIRE_SMALL FIRE_MED FIRE_MED2 FIRE_TINY MUZZLE_FLASH SMOKE_M BURN_SMALL
BURN_MED BURN_BIG ON_FIRE_SMALL ON_FIRE_MED ON_FIRE_BIG SAM_N SAM_NE SAM_E SAM_SE
SAM_S SAM_SW SAM_W SAM_NW GUN_N GUN_NE GUN_E GUN_SE GUN_S GUN_SW GUN_W GUN_NW
LZ_SMOKE ION_CANNON ATOM_BLAST CRATE_DEVIATOR CRATE_DOLLAR CRATE_EARTH
CRATE_EMPULSE CRATE_INVUN CRATE_MINE CRATE_RAPID CRATE_STEALTH CRATE_MISSILE
ATOM_DOOR MOVE_FLASH OILFIELD_BURN TRIC_DIE TREX_DIE STEG_DIE RAPT_DIE CHEM_BALL
FLAG BEACON FIRE_SMALL_VIRTUAL FIRE_MED_VIRTUAL FIRE_MED2_VIRTUAL
FIRE_TINY_VIRTUAL BEACON_VIRTUAL""".split()

# The DOS anims the cartridge simply does not have, each with its reason. The script
# REFUSES to emit if a DOS anim is neither in the cartridge table nor listed here, so a
# future JSON regeneration cannot silently drop an anim.
#   CHEM_*      the N64 table has no chem entries at all (Chem Warrior is DOS-only art)
#   *_DIE       the Covert Ops dinosaurs
#   CHEM_BALL, FLAG, BEACON   Covert Ops / multiplayer extras
#   *_VIRTUAL   the GlyphX shadow companions. anim.cpp:684 calls Make_Invisible() on
#               them and anim.cpp:231 gates render_legacy on !IsInvisible, so the 1995
#               renderer never draws them either. Mapping them to -1 is what stops us
#               drawing every fire twice.
NO_N64 = set(n for n in DOS if n.startswith("CHEM_") or n.endswith("_DIE")
             or n.endswith("_VIRTUAL") or n in ("CHEM_BALL", "FLAG", "BEACON"))

# gGameParticleSystems, BSS 0x800EC1B0, stride 0x34; names from the ROM's own registry
# at ROM 0xA2BD4. The order IS the system index the source records store.
SYS = ["Intensity", "FireBall", "VehicleDamage", "StructureDamage", "Shock",
       "Burn_Fire", "Burn_Smoke", "Ion_Spark", "Debris", "FlameThrower"]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        here, "..", "tools", "romdump", "particle_recipes.json")
    d = json.load(open(path))

    order = [a["anim"][5:] for a in d["anims"]]           # strip the "ANIM_" prefix
    idx = {n: i for i, n in enumerate(order)}
    src = {s["id"]: s for s in d["sources"]}
    vis = d["visuals"]

    for n in DOS:
        if n not in NO_N64 and n not in idx:
            sys.exit("gen_efx_recipes: DOS anim %s has no N64 entry and is not listed "
                     "as absent -- decide before generating" % n)
    if len(d["sources"]) != 65:
        sys.exit("gen_efx_recipes: expected 65 source records, got %d"
                 % len(d["sources"]))

    o = sys.stdout.write
    o("/* GENERATED by game/gen_efx_recipes.py from tools/romdump/particle_recipes.json.\n"
      "   DO NOT EDIT BY HAND -- re-run the generator. Every number below is the\n"
      "   cartridge's own: anim table ROM 0x1B6444, source table ROM 0x1B41C0, visual\n"
      "   sub-records ROM 0xA2C2C+. Units are WORLD UNITS, 256 to the cell (the JSON's\n"
      "   _meta string says 192; it is wrong, see this file's generator header). */\n"
      "#ifndef CNC3D_EFX_RECIPES_H\n#define CNC3D_EFX_RECIPES_H\n\n")

    # ---- sources -----------------------------------------------------------
    o("struct EfxSourceRec {\n"
      "    const char*   name;         /* the ROM's own SOURCE_* string, minus prefix */\n"
      "    unsigned char sys;          /* particle system index; see EFX_SYS          */\n"
      "    unsigned char nvar;         /* visual variants (only Debris/Debris2 have 2)*/\n"
      "    float ppt, mult;            /* +0x10 particles/tick, +0x14 multiplier      */\n"
      "    short burst;                /* +0x18 ticks; 0 = continuous (re-armed)      */\n"
      "    float spd, spdR;            /* +0x1C/+0x20 world units per tick            */\n"
      "    short life, lifeR;          /* +0x24/+0x28 ticks                           */\n"
      "    float size, sizeR;          /* +0x2C/+0x30 world units (a diameter)        */\n"
      "    float aMin, aMax, bMin, bMax;   /* +0x34..+0x40 radians                    */\n"
      "    float yacc, grow;           /* visual +0x20 accel.y, +0x2C size growth/tick*/\n"
      "    unsigned char a, r, g, b;   /* visual +0x32..+0x35                         */\n"
      "    unsigned char arate;        /* visual +0x31, the ALPHA RAMP SLOPE per tick  */\n"
      "};\n\n"
      "static const EfxSourceRec EFX_SRC[65] = {\n")
    for i in range(65):
        s = src[i]
        v = vis[s["visual_ram"]]["records"][0]
        raw = v["raw_30"].replace(" ", "")
        by = [int(raw[j:j + 2], 16) for j in range(0, len(raw), 2)]
        o("  { \"%s\", %d, %d, %.6ff, %.6ff, %d, %.6ff, %.6ff, %d, %d, %.6ff, %.6ff,"
          " %.6ff, %.6ff, %.6ff, %.6ff, %.6ff, %.6ff, %d, %d, %d, %d, 0x%02x },\n" % (
              s["name"][7:], SYS.index(s["system"]), s["visual_variants"],
              s["particles_per_tick"], s["per_tick_multiplier"], s["burst_ticks"],
              s["speed_base"], s["speed_rand"], s["life_base"], s["life_rand"],
              s["size_base"], s["size_rand"],
              s["angle_a_min"], s["angle_a_max"], s["angle_b_min"], s["angle_b_max"],
              v["y_accel_per_tick"], v["f2C"], by[2], by[3], by[4], by[5], by[1]))
    o("};\n\n")
    o("/* `arate` is the visual sub-record byte +0x31: the ALPHA RAMP SLOPE.
   alpha = min(lifeLeft * arate, cap). The frame index comes from age/life alone.
   See efx_recipes.h for the full ROM trail. */\n\n")

    # ---- the second Debris visual variant (the pale chunk) -----------------
    v0 = vis["0x800A202C"]["records"][0]
    v1 = vis["0x800A202C"]["records"][1]
    raw = v1["raw_30"].replace(" ", "")
    by = [int(raw[j:j + 2], 16) for j in range(0, len(raw), 2)]
    o("/* SOURCE_Debris / _Debris2 declare TWO visual variants: identical physics\n"
      "   (y accel %.1f per tick^2, elasticity %.2f) with colour %d,%d,%d instead of\n"
      "   the burnt orange of variant 0. Both are on screen in the reference frames\n"
      "   (p080: dark-red chunks AND white-grey chunks leaving the same blast). */\n"
      "static const unsigned char EFX_DEBRIS_VAR1[4] = { %d, %d, %d, %d };\n"
      "static const float EFX_CHUNK_YACC   = %.6ff;   /* world units per tick^2 */\n"
      "static const float EFX_CHUNK_BOUNCE = %.6ff;   /* visual +0x28 elasticity */\n\n"
      % (v1["y_accel_per_tick"], v1["damping"], by[3], by[4], by[5],
         by[2], by[3], by[4], by[5],
         v0["y_accel_per_tick"], v0["damping"]))

    # ---- anims -------------------------------------------------------------
    o("/* One slot = one emitter the anim instantiates. dx/dz are world-unit offsets\n"
      "   from the anim's own cell; dy is added to the TERRAIN HEIGHT under (x,z), not\n"
      "   to the anim's y (spawn wrapper RAM 0x801FC918 calls the ground-height fn and\n"
      "   adds dy to its result). A slot fires when the anim's stage reaches its\n"
      "   fire_stage: burst sources exactly once, continuous sources every stage. */\n"
      "struct EfxSlot { unsigned char src, stage; short dx, dy, dz; };\n"
      "struct EfxRecipe { const char* name; unsigned char nslot; EfxSlot slot[10]; };\n\n"
      "static const EfxRecipe EFX_RECIPE[%d] = {\n" % len(order))
    empties = []
    for a in d["anims"]:
        ss = a["sources"]
        if not ss:
            empties.append(a["anim"][5:])
        o("  { \"%s\", %d, {" % (a["anim"][5:], len(ss)))
        for s in ss:
            o(" {%d,%d,%d,%d,%d}," % (s["source_id"], s["fire_stage"],
                                      s["offset"][0], s["offset"][1], s["offset"][2]))
        o(" } },\n")
    o("};\n\n")
    o("/* %d of the %d cartridge anims have every slot empty. That is a DECISION in the\n"
      "   ROM, not a gap in the decode: the spawn wrapper skips a zero source_id\n"
      "   (RAM 0x801FC884) and there is no fallback source anywhere in it. They are:\n"
      "   %s. */\n\n" % (len(empties), len(order), ", ".join(empties)))

    # ---- DOS AnimType -> recipe index --------------------------------------
    o("/* The engine's AnimType -> the cartridge's anim-table index. NOT the identity:\n"
      "   the N64 enum gained ANIM_FRAG3 (its index 4) and dropped the eight\n"
      "   ANIM_CHEM_*, so everything after ANIM_FRAG2 is shifted by +1 and then by -7.\n"
      "   -1 means the cartridge has no such anim at all; an EMPTY recipe (nslot 0) is\n"
      "   a different thing entirely -- there the console deliberately spawns nothing.\n"
      "   INDEX THIS WITH `type=`, NEVER WITH THE ART NAME. */\n"
      "static const signed char EFX_ANIM2RECIPE[%d] = {\n" % len(DOS))
    for i, n in enumerate(DOS):
        r = -1 if n in NO_N64 else idx[n]
        o("  %3d, /* %2d ANIM_%s%s */\n" % (
            r, i, n, "" if r >= 0 else "   -- no N64 counterpart"))
    o("};\n"
      "static const int EFX_ANIM2RECIPE_N = %d;\n\n"
      "#endif /* CNC3D_EFX_RECIPES_H */\n" % len(DOS))


main()
