/* hud640_layout.h -- GENERATED by tools/sidebar_redesign/bake_pack.py.
 * Do not edit: re-run the baker. Every number here was MEASURED off the reference art
 * by slice_ref.py, not chosen by hand. */
#ifndef HUD640_LAYOUT_H
#define HUD640_LAYOUT_H

/* the sidebar column, and the tab strip that runs left of it */
#define H6_SCREEN_W  640
#define H6_SCREEN_H  480
#define H6_BAR_W     160
#define H6_BAR_H     480
#define H6_BAR_X     (H6_SCREEN_W - H6_BAR_W)   /* 480 */
#define H6_TAB_H     17
#define H6_OPT_X     0
#define H6_CREDITS_X 320

/* radar surface, in sidebar-local pixels */
#define H6_RADAR_X   11
#define H6_RADAR_Y   31
#define H6_RADAR_W   136
#define H6_RADAR_H   120

/* build grid */
#define H6_CELL_W    61
#define H6_CELL_H    45

/* The CAMEO box. Bigger than the well on purpose: C&C95 cameos are 64x48 and the
 * caption runs edge to edge along the bottom, so cropping them to the well took the
 * first and last letter of every name. They are drawn at native size, centred on the
 * well, overhanging it by 1-2px - which is also how C&C95 looks, cameos butted together.
 * 64x48 is exactly 2x the DOS cameo, so the fallback lands in the same box. */
#define H6_CAMEO_W   64
#define H6_CAMEO_H   48
#define H6_CAMEO_DX  ((H6_CELL_W - H6_CAMEO_W) / 2)
#define H6_CAMEO_DY  ((H6_CELL_H - H6_CAMEO_H) / 2)
#define H6_COLUMNS   2
#define H6_ROWS      5
static const int H6_COL_X[2] = {18, 87};
static const int H6_ROW_Y[5] = {210, 259, 306, 353, 401};

/* power meter: a channel filled bottom-up with one repeating segment */
#define H6_METER_X   0
#define H6_METER_Y0  211
#define H6_METER_W   17
#define H6_METER_H   238
#define H6_METER_PITCH 12

/* interactive elements: x, y, w, h, frame count */
#define H6_BTN_REPAIR_X 6
#define H6_BTN_REPAIR_Y 184
#define H6_BTN_REPAIR_W 56
#define H6_BTN_REPAIR_H 23
#define H6_BTN_REPAIR_FRAMES 4
#define H6_BTN_SELL_X 71
#define H6_BTN_SELL_Y 184
#define H6_BTN_SELL_W 34
#define H6_BTN_SELL_H 23
#define H6_BTN_SELL_FRAMES 4
#define H6_BTN_MAP_X 115
#define H6_BTN_MAP_Y 184
#define H6_BTN_MAP_W 35
#define H6_BTN_MAP_H 23
#define H6_BTN_MAP_FRAMES 3
#define H6_ARROW_UP_X 18
#define H6_ARROW_UP_Y 453
#define H6_ARROW_UP_W 32
#define H6_ARROW_UP_H 25
#define H6_ARROW_UP_FRAMES 3
#define H6_ARROW_DOWN_X 53
#define H6_ARROW_DOWN_Y 453
#define H6_ARROW_DOWN_W 32
#define H6_ARROW_DOWN_H 25
#define H6_ARROW_DOWN_FRAMES 3

/* the four scroll arrows sit on one row */
static const int H6_ARROW_X[4] = {18, 53, 88, 123};
#define H6_ARROW_Y   453

#endif /* HUD640_LAYOUT_H */
