"""Bake the HUD chunks into playable/hud640.pack, plus a generated C layout header.

The engine has no PNG decoder (video/pngwrite.h is write-only), so assets go in as raw
RGBA in one flat pack, the same shape as dossidebar.pack. The layout header is GENERATED
from chunks/layout.json so the coordinates are never retyped by hand."""
from PIL import Image
import struct, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CH   = os.path.join(HERE, "chunks")
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PACK = os.path.join(ROOT, "playable", "hud640.pack")
HDR  = os.path.join(ROOT, "game", "hud640_layout.h")

MAGIC = b"CNCHUD01"

# name -> (file, frames)
ASSETS = [
    ("chassis",      "chassis_blank.png",      1),
    ("tab_plate",    "tab_plate.png",          3),
    ("tab_options",  "tab_options.png",        3),
    ("tab_sidebar",  "tab_sidebar.png",        3),
    ("tab_database", "tab_database.png",       3),
    ("radar_off",    "radar_off_gdi.png",      1),
    ("radar_off_nod","radar_off_nod.png",      1),
    ("meter_lit",    "meter_segment_lit.png",  1),
    ("meter_unlit",  "meter_segment_unlit.png",1),
    ("digits",       "digits_strip.png",      10),
    # None means "ask frames.json". states.py owns how many states a control has, and
    # duplicating that count here is how the two drifted apart the first time.
    ("btn_repair",   "button_repair.png",   None),
    ("btn_sell",     "button_sell.png",     None),
    ("btn_map",      "button_map.png",      None),
    ("arrow_up",     "arrow_up.png",        None),
    ("arrow_down",   "arrow_down.png",      None),
    ("cell_well",    "cell_well.png",          1),
    ("cell_frame",   "cell_frame.png",         1),
    # The power meter's DRAIN MARKER: the strip that says how much of the channel the
    # base is spoken for, which is what makes the meter show consumption and not output
    # alone. Drawn by meter_mark.py from the DOS gauge's own POWER shape. It sat here as
    # OPTIONAL while the chunk was owed, and that is exactly how a release shipped with
    # every line of the feature in place and the feature invisible, so there is no such
    # category any more: a chunk named in this table and missing from disk is an error.
    ("meter_drain",  "meter_drain_mark.png",   1),
]

def bake():
    lay = json.load(open(f"{CH}/layout.json"))
    frm = json.load(open(f"{CH}/frames.json"))
    out = bytearray()
    table = []
    for name, fn, frames in ASSETS:
        p = os.path.join(CH, fn)
        if not os.path.exists(p):
            sys.exit("missing chunk: %s" % p)
        if frames is None:
            stem = os.path.splitext(fn)[0]
            if stem not in frm:
                sys.exit("%s: no entry in frames.json" % stem)
            frames = frm[stem]["frames"]
        im = Image.open(p).convert("RGBA")
        if im.width % frames:
            sys.exit("%s: width %d not divisible by %d frames" % (fn, im.width, frames))
        fw, fh = im.width // frames, im.height
        table.append((name, fw, fh, frames, im.tobytes()))
    # len(TABLE), not len(ASSETS): the two agree only while every chunk is on disk, and
    # the larger number would make hud640_load walk an entry nothing wrote.
    out += MAGIC + struct.pack("<II", 1, len(table))
    for name, fw, fh, frames, blob in table:
        out += name.encode().ljust(16, b"\0")
        out += struct.pack("<III", fw, fh, frames)
        out += blob
        print("  %-12s %3dx%-3d x%d  %6d bytes" % (name, fw, fh, frames, len(blob)))
    os.makedirs(os.path.dirname(PACK), exist_ok=True)
    open(PACK, "wb").write(bytes(out))
    print("\nwrote %s  (%.0f KB)" % (PACK, len(out)/1024))

    rx, ry, rw, rh = lay["RADAR"]; cw, chh = lay["CELL"]
    mx, my, mw, mh = lay["METER"]
    # WRITE TO A BUFFER, NOT TO THE FILE, AND ONLY TOUCH THE FILE IF THE BYTES CHANGED.
    # hud640_layout.h is a compile INPUT (hud640.h takes every coordinate from it), and
    # this baker runs after the compiles in make-build.sh. Rewriting identical bytes still
    # moves the mtime, which left every binary a second older than a header it had already
    # compiled against, and G30 reported STALE on a perfectly good build. An idempotent
    # generator must be idempotent in the FILESYSTEM too, not just in its output.
    import io as _io
    h = _io.StringIO()
    if True:
        h.write("""/* hud640_layout.h -- GENERATED by tools/sidebar_redesign/bake_pack.py.
 * Do not edit: re-run the baker. Every number here was MEASURED off the reference art
 * by slice_ref.py, not chosen by hand. */
#ifndef HUD640_LAYOUT_H
#define HUD640_LAYOUT_H

""")
        h.write("/* the sidebar column, and the tab strip that runs left of it */\n")
        h.write("#define H6_SCREEN_W  640\n#define H6_SCREEN_H  480\n")
        h.write("#define H6_BAR_W     160\n#define H6_BAR_H     480\n")
        h.write("#define H6_BAR_X     (H6_SCREEN_W - H6_BAR_W)   /* 480 */\n")
        h.write("#define H6_TAB_H     17\n")
        h.write("#define H6_OPT_X     0\n#define H6_CREDITS_X 320\n\n")
        h.write("/* radar surface, in sidebar-local pixels */\n")
        h.write("#define H6_RADAR_X   %d\n#define H6_RADAR_Y   %d\n" % (rx, ry))
        h.write("#define H6_RADAR_W   %d\n#define H6_RADAR_H   %d\n\n" % (rw, rh))
        h.write("/* build grid */\n")
        h.write("#define H6_CELL_W    %d\n#define H6_CELL_H    %d\n" % (cw, chh))
        h.write("""
/* The CAMEO box. Bigger than the well on purpose: C&C95 cameos are 64x48 and the
 * caption runs edge to edge along the bottom, so cropping them to the well took the
 * first and last letter of every name. They are drawn at native size, centred on the
 * well, overhanging it by 1-2px - which is also how C&C95 looks, cameos butted together.
 * 64x48 is exactly 2x the DOS cameo, so the fallback lands in the same box. */
#define H6_CAMEO_W   64
#define H6_CAMEO_H   48
#define H6_CAMEO_DX  ((H6_CELL_W - H6_CAMEO_W) / 2)
#define H6_CAMEO_DY  ((H6_CELL_H - H6_CAMEO_H) / 2)
""")
        h.write("#define H6_COLUMNS   %d\n#define H6_ROWS      %d\n" % (len(lay["COLS"]), len(lay["ROWS"])))
        h.write("static const int H6_COL_X[%d] = {%s};\n" % (len(lay["COLS"]), ", ".join(map(str, lay["COLS"]))))
        h.write("static const int H6_ROW_Y[%d] = {%s};\n\n" % (len(lay["ROWS"]), ", ".join(map(str, lay["ROWS"]))))
        h.write("/* power meter: a channel filled bottom-up with one repeating segment */\n")
        h.write("#define H6_METER_X   %d\n#define H6_METER_Y0  %d\n" % (mx, my))
        h.write("#define H6_METER_W   %d\n#define H6_METER_H   %d\n" % (mw, mh))
        h.write("#define H6_METER_PITCH %d\n\n" % lay["PITCH"])
        h.write("/* interactive elements: x, y, w, h, frame count */\n")
        for k in ("button_repair", "button_sell", "button_map", "arrow_up", "arrow_down"):
            d = frm[k]; K = k.upper().replace("BUTTON", "BTN")
            h.write("#define H6_%s_X %d\n#define H6_%s_Y %d\n" % (K, d["x"], K, d["y"]))
            h.write("#define H6_%s_W %d\n#define H6_%s_H %d\n" % (K, d["w"], K, d["h"]))
            h.write("#define H6_%s_FRAMES %d\n" % (K, d["frames"]))
        h.write("\n/* the four scroll arrows sit on one row */\n")
        h.write("static const int H6_ARROW_X[4] = {18, 53, 88, 123};\n")
        h.write("#define H6_ARROW_Y   %d\n" % frm["arrow_up"]["y"])
        h.write("\n#endif /* HUD640_LAYOUT_H */\n")
    new = h.getvalue()
    try:
        old = _io.open(HDR, encoding="utf-8").read()
    except IOError:
        old = None
    if old == new:
        print("unchanged %s" % HDR)
    else:
        with _io.open(HDR, "w", encoding="utf-8") as f:
            f.write(new)
        print("wrote %s" % HDR)

if __name__ == "__main__":
    bake()
