; Written by the CNC3D map editor. Cells are y*64 + x.
[Basic]
Name=SCA01EA
Player=GoodGuy
CarryOverMoney=0
BuildLevel=7
Theme=No theme
Intro=x
Brief=x
Action=x
Win=x
Lose=x
Percent=0
CNC3DKind=Single

[MAP]
Theater=DESERT
CNC3DTheater=SAND
X=10
Y=10
Width=44
Height=44

[GoodGuy]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=GoodGuy
Edge=North

[BadGuy]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=BadGuy
Edge=North

[Neutral]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=Neutral
Edge=North

[Special]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=Special
Edge=North

[Waypoints]
25=2013
26=2018
27=2338

[Triggers]

[CellTriggers]

[TeamTypes]

[TERRAIN]

[OVERLAY]

[SMUDGE]

[STRUCTURES]

[UNITS]

[INFANTRY]
