#!/usr/bin/env python3
"""codex.json -> game/codex_table.h, the table the DATABASE screen compiles in.

WHY A GENERATED HEADER AND NOT A PACK. Every other art payload in this game is a pack
because it is megabytes of pixels; this is fifty rows of small integers and short strings,
about 12 KB. A header costs no runtime file I/O, cannot go stale against a build, and
cannot be missing from a run folder -- three failure modes the pack path has and this one
does not need to inherit. If the manual copy lands and the strings grow by an order of
magnitude, moving it to a pack is a contained change.

The roster is BUILDABLE, HOUSE-OWNED, NON-CIVILIAN: the fifty things a player can put on
the field. Everything else in the type tables -- the 37 civilian buildings, the ten named
civilians, the dinosaurs, the A10 and the C17 the engine flies in by itself -- stays out,
because a codex is a build reference and not a dump of the type tables.

Run it after codex_data.py; gate G-codex re-runs both and diffs the header, so a change
to the GPL source or to the reader shows up as a failing gate rather than as a screen
quietly disagreeing with the game.
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.environ.get("CNC3D_ROOT") or os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(ROOT, "game", "codex_table.h")

CATS = [("Structures", "STRUCTURES"), ("Infantry", "INFANTRY"),
        ("Vehicles", "VEHICLES"), ("Aircraft", "AIRCRAFT")]


def cstr(s):
    if s is None:
        return "NULL"
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    return '"%s"' % out


def names(units, limit=3):
    return ", ".join(u["name"] for u in units[:limit])


def main():
    src = os.path.join(HERE, "codex.json")
    if not os.path.exists(src):
        subprocess.check_call([sys.executable, os.path.join(HERE, "codex_data.py")])
    d = json.load(open(src))

    rows = [e for e in d["entries"]
            if e["buildable"] and e["houses"] and not e["is_civilian"]]
    # Tech level first, then cost: the order a player meets them, which is the order the
    # sidebar offers them in. Code last so the sort is total and the header is stable
    # byte for byte between runs -- a generated file that reshuffles is a generated file
    # nobody can diff.
    rows.sort(key=lambda e: (e["level"] if e["level"] is not None else 99,
                             e["cost"] or 0, e["code"]))

    mx = d["maxima"]
    L = []
    A = L.append
    A("/* ==================================================================================")
    A(" *  codex_table.h -- the DATABASE screen's rows.")
    A(" *")
    A(" *  GENERATED by tools/database_codex/gen_codex_table.py out of")
    A(" *  tools/database_codex/codex.json, which tools/database_codex/codex_data.py reads")
    A(" *  straight out of EA's GPL Tiberian Dawn source. DO NOT EDIT THIS FILE: run the")
    A(" *  two scripts. Every number below is the 1995 engine's own, positionally decoded")
    A(" *  against the constructor signatures in brain/vanilla/tiberiandawn/type.h.")
    A(" *")
    A(" *  `brief` is DERIVED from those same fields and is NOT the 1995 manual's copy.")
    A(" *  The manual is not in this repository, so writing a paragraph in its voice would")
    A(" *  be inventing 1995 text. Dropping the real copy in when it exists is a change to")
    A(" *  codex_data.py's brief(), not to this screen.")
    A(" * ================================================================================== */")
    A("")
    A("#ifndef CODEX_TABLE_H")
    A("#define CODEX_TABLE_H")
    A("")
    A("#define CODEX_CATS %d" % len(CATS))
    for i, (_k, n) in enumerate(CATS):
        A("#define CODEX_CAT_%-12s %d" % (n, i))
    A("")
    A("static const char* const CODEX_CAT_NAME[CODEX_CATS] = {")
    A("    " + ", ".join(cstr(n) for _k, n in CATS))
    A("};")
    A("")
    A("#define CODEX_HOUSE_GDI 1u")
    A("#define CODEX_HOUSE_NOD 2u")
    A("")
    A("/* THE BAR SCALES. One per stat for the WHOLE table, so two entries can be compared")
    A("   by eye; computed across every row rather than picked. ROF is ticks BETWEEN shots,")
    A("   so its bar is drawn inverted while the printed number stays the source's. */")
    A("#define CODEX_MAX_HP     %d" % mx["hitpoints"])
    A("#define CODEX_MAX_DAMAGE %d" % mx["damage"])
    A("#define CODEX_MAX_SPEED  %d" % mx["speed"])
    A("#define CODEX_MAX_ROF    %d" % mx["rate"])
    A("#define CODEX_MAX_COST   %d" % mx["cost"])
    A("")
    A("typedef struct {")
    A("    const char* code;      /* INI ident; also the pack's mesh key */")
    A("    const char* name;      /* the 1995 display name, from conquer.h */")
    A("    const char* brief;     /* derived, see the header note */")
    A("    int         cat;       /* CODEX_CAT_* */")
    A("    unsigned    houses;    /* CODEX_HOUSE_* bit field */")
    A("    int         hitpoints; /* STRENGTH */")
    A("    int         cost;      /* credits */")
    A("    int         speed;     /* MPH; -1 where the family has no speed */")
    A("    int         damage;    /* primary weapon damage; -1 unarmed */")
    A("    int         rof;       /* ticks between shots; -1 unarmed */")
    A("    int         range256;  /* weapon range in leptons, 256 to the cell */")
    A("    const char* armour;")
    A("    const char* strong;    /* what its warhead beats, by name */")
    A("    const char* weak;      /* what beats its armour, by name */")
    A("    const char* unlocks;   /* what names it as a prerequisite */")
    A("} CodexRow;")
    A("")
    A("static const CodexRow CODEX[] = {")
    for e in rows:
        p = e.get("primary")
        house = 0
        house |= 1 if "GDI" in e["houses"] else 0
        house |= 2 if "NOD" in e["houses"] else 0
        cat = next(i for i, (k, _n) in enumerate(CATS) if k == e["category"])
        A("    { %s, %s," % (cstr(e["code"]), cstr(e["name"])))
        A("      %s," % cstr(e["brief"]))
        A("      %d, %du, %d, %d, %d, %d, %d, %d, %s," % (
            cat, house,
            e["hitpoints"] if e["hitpoints"] is not None else -1,
            e["cost"] if e["cost"] is not None else -1,
            e["speed"] if e["speed"] is not None else -1,
            p["damage"] if p else -1,
            p["rof"] if p else -1,
            p["range"] if p else -1,
            cstr(d["armor_label"].get(e["armor"], "-"))))
        A("      %s," % cstr(names(e["strong_against"]["units"])))
        A("      %s," % cstr(names(e["weak_against"]["units"])))
        A("      %s }," % cstr(", ".join(e["unlock_names"][:4])))
    A("};")
    A("")
    A("#define CODEX_N ((int)(sizeof CODEX / sizeof CODEX[0]))")
    A("")
    A("#endif /* CODEX_TABLE_H */")

    text = "\n".join(L) + "\n"
    old = open(OUT).read() if os.path.exists(OUT) else None
    open(OUT, "w").write(text)
    print("%s: %d rows, %d bytes%s"
          % (os.path.relpath(OUT, ROOT), len(rows), len(text),
             "" if old == text else "  (CHANGED)"))
    for i, (k, n) in enumerate(CATS):
        print("   %-11s %d" % (n, sum(1 for e in rows if e["category"] == k)))


if __name__ == "__main__":
    main()
