; Written by the CNC3D map editor. Cells are y*128 + x.
[Basic]
Name=USER91
Player=GoodGuy
CarryOverMoney=0
BuildLevel=7
Theme=No theme
Intro=x
Brief=x
Action=x
Win=x
Lose=x
Percent=0

CNC3DKind=Multi
[MAP]
Version=1
Theater=TEMPERATE
CNC3DTheater=TEMPERATE
X=4
Y=4
Width=120
Height=120

[GoodGuy]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=GoodGuy
Edge=North

[BadGuy]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=BadGuy
Edge=North

[Neutral]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=Neutral
Edge=North

[Special]
Credits=5000
MaxBuilding=150
MaxUnit=150
Allies=Special
Edge=North




[Waypoints]
27=-1
26=-1
25=-1
24=-1
23=-1
22=-1
21=-1
20=-1
19=-1
18=-1
17=-1
16=-1
15=-1
14=-1
13=-1
12=-1
11=-1
10=-1
9=-1
8=-1
7=15296
6=8311
5=8200
4=1088
3=15351
2=15240
1=1143
0=1032

[TERRAIN]

[OVERLAY]

[SMUDGE]

[STRUCTURES]
000=GoodGuy,FACT,256,2580,0,None
001=GoodGuy,PYLE,256,2584,0,None
002=BadGuy,HAND,256,12890,0,None

[UNITS]

[INFANTRY]
000=GoodGuy,E1,256,2842,0,Guard,96,None
001=BadGuy,E1,256,12892,0,Guard,96,None
