#!/usr/bin/env python3
"""Write an XL-native test scenario: a square map at any tier the XL brain supports.

    make-xl-map.py <outdir> <name> <size> [--stride N] [--houses N] [--army N] [--pair D]

WHY THIS EXISTS RATHER THAN AN AUTHORED MAP. The mission editor writes the 128-wide
format, and the 128-wide format cannot express a map bigger than itself: its sparse .BIN
key is sixteen bits and its cell numbers carry no stride. So the first XL-native content
has to be generated, and it has to be generated by something that states the format in one
place rather than by hand.

WHAT IT MAKES. A playable-shaped scenario, not a pretty one: clear ground with a border of
rock so the edges are visible, a tiberium field per player, one start waypoint per player
spread evenly around the map, and a construction yard plus a couple of units for each. That
is enough to boot, to path across the whole map, and to have something die.

THE FORMAT, matching MapClass::Read_Binary_XL:
    header  4s magic 'C3XB', u16 version 2, u16 stride, u32 count
    record  u32 cell, u8 template, u8 icon, u16 pad
Cell numbers ARE the brain's own, at the fixed 1024 stride, in the INI as well as the .BIN.
"""
import os
import struct
import sys

MAGIC = b'C3XB'
MAP_VERSION_XL = 2
DEFAULT_STRIDE = 1024

# Template ids from the temperate/desert banks that every theater carries.
T_CLEAR = 255       # TEMPLATE_NONE: the reader turns 255 into clear
T_WATER = 1         # TEMPLATE_WATER

# Each start gets one of these, alternating, so both sides are exercised.
SIDES = ["GoodGuy", "BadGuy"]


def cell(x, y, stride):
    return y * stride + x


def write_bin(path, tiles, stride):
    """tiles: dict of cell -> (template, icon)."""
    with open(path, "wb") as f:
        f.write(struct.pack("<4sHHI", MAGIC, MAP_VERSION_XL, stride, len(tiles)))
        for c in sorted(tiles):
            tmpl, icon = tiles[c]
            f.write(struct.pack("<IBBH", c, tmpl, icon, 0))


def write_hgt(path, size):
    """The corner heightfield the RENDERER reads. The brain never opens it, but a map
    without one is a map the host cannot draw, and a flat field is the honest default."""
    with open(path, "wb") as f:
        f.write(bytes((size + 1) * (size + 1)))


def build(outdir, name, size, stride, houses, army, pair):
    if size > stride:
        sys.exit("a %d map does not fit a %d stride" % (size, stride))
    if houses < 1 or houses > 8:
        sys.exit("houses must be 1..8 (the classic house set; the 64-house tier is later)")

    # A rim of water two cells deep, so the map's own edges are visible in any dump and
    # nothing can walk off the side without it showing.
    tiles = {}
    for i in range(size):
        for d in (0, 1, size - 2, size - 1):
            tiles[cell(i, d, stride)] = (T_WATER, 0)
            tiles[cell(d, i, stride)] = (T_WATER, 0)

    # Starts evenly around a circle inset from the rim, which keeps every pair of players
    # a long walk apart -- the case the classic pathfinder's 400-entry bound fails on.
    #
    # --pair D OVERRIDES THAT, and it exists because the circle CONFOUNDS the experiment
    # it looks like it is running. Scaling the ring with the map means a bigger map also
    # means a longer walk, so "nothing happened at 1024" has two available explanations
    # and the measurement cannot tell them apart. --pair fixes the distance between two
    # players in cells and lets the map size vary underneath it, which separates "this
    # trek is too long" from "this map is too wide".
    import math
    starts = []
    if pair:
        cx, cy = size // 2, size // 2
        half = pair // 2
        if cx - half < 4 or cx + half >= size - 4:
            sys.exit("a %d cell separation does not fit a %d map" % (pair, size))
        starts = [(cx - half, cy), (cx + half, cy)]
        houses = 2
    else:
        inset = max(6, size // 8)
        r = (size // 2) - inset
        for i in range(houses):
            a = 2.0 * math.pi * i / houses
            sx = int(size / 2 + r * math.cos(a))
            sy = int(size / 2 + r * math.sin(a))
            starts.append((sx, sy))

    lines = []
    lines.append("; XL-native test scenario, generated by tools/xl-parity/make-xl-map.py.")
    lines.append("; Cells are y*%d + x: this brain's own numbering, which is what Version=%d means."
                 % (stride, MAP_VERSION_XL))
    lines.append("[Basic]")
    lines.append("Name=%s" % name)
    lines.append("Player=%s" % SIDES[0])
    lines.append("CarryOverMoney=0")
    lines.append("BuildLevel=7")
    lines.append("Theme=No theme")
    for k in ("Intro", "Brief", "Action", "Win", "Lose"):
        lines.append("%s=x" % k)
    lines.append("Percent=0")
    lines.append("CNC3DKind=Multi")
    lines.append("")
    # THE SQUARE THE MAP OCCUPIES, which [MAP] does not state. X/Y/Width/Height are the
    # PLAYABLE RECT inside a border; the array the map lives in is larger, and for the
    # older formats it was implied by the .BIN's own length. A sparse file has no length
    # to read it from, so an XL map says it.
    lines.append("[CNC3D]")
    lines.append("Grid=%d" % size)
    lines.append("")
    lines.append("[MAP]")
    lines.append("Version=%d" % MAP_VERSION_XL)
    lines.append("Theater=TEMPERATE")
    lines.append("CNC3DTheater=TEMPERATE")
    lines.append("X=2")
    lines.append("Y=2")
    lines.append("Width=%d" % (size - 4))
    lines.append("Height=%d" % (size - 4))
    lines.append("")

    for h in ("GoodGuy", "BadGuy", "Neutral"):
        lines.append("[%s]" % h)
        lines.append("Credits=10000")
        lines.append("MaxBuilding=150")
        lines.append("MaxUnit=150")
        lines.append("Allies=%s" % h)
        lines.append("Edge=North")
        lines.append("")

    lines.append("[Special]")
    lines.append("")

    lines.append("[Waypoints]")
    for i, (sx, sy) in enumerate(starts):
        lines.append("%d=%d" % (i, cell(sx, sy, stride)))
    # HOME and REINFORCE, at the classic indices.
    lines.append("25=%d" % cell(starts[0][0], starts[0][1], stride))
    lines.append("26=%d" % cell(starts[0][0], starts[0][1], stride))
    lines.append("")

    # A tiberium field beside every start, so harvesting and the growth scan both have
    # something to do wherever the map is walked.
    lines.append("[OVERLAY]")
    for (sx, sy) in starts:
        for dy in range(-3, 4):
            for dx in range(-3, 4):
                x, y = sx + dx + 8, sy + dy
                if 2 <= x < size - 2 and 2 <= y < size - 2:
                    lines.append("%d=TI12" % cell(x, y, stride))
    lines.append("")

    lines.append("[STRUCTURES]")
    n = 0
    for i, (sx, sy) in enumerate(starts):
        side = SIDES[i % len(SIDES)]
        lines.append("%03d=%s,FACT,256,%d,0,None" % (n, side, cell(sx, sy, stride)))
        n += 1
        lines.append("%03d=%s,POWR,256,%d,0,None" % (n, side, cell(sx + 3, sy, stride)))
        n += 1
    lines.append("")

    # THE ARMY IS THE LOAD TEST. One unit apiece proves the map loads; a real tick cost
    # needs bodies, and bodies on ATTACK orders rather than Guard, because the expensive
    # things at this scale are pathfinding and target scans, and Guard does neither.
    # Hunt sends each unit at the nearest enemy, which on a circle of starts is the
    # longest walk the map affords -- the case the classic edge-follower is expected to
    # fail at, and the reason the pathfinder is a ship blocker for the 256 tier.
    lines.append("[UNITS]")
    n = 0
    for i, (sx, sy) in enumerate(starts):
        side = SIDES[i % len(SIDES)]
        lines.append("%d=%s,MCV,256,%d,0,Guard,None" % (n, side, cell(sx, sy + 3, stride)))
        n += 1
        lines.append("%d=%s,HARV,256,%d,0,Harvest,None" % (n, side, cell(sx + 1, sy + 3, stride)))
        n += 1
        for k in range(army):
            # A block beside the start, walked outward so a big army still fits inside
            # the map and never lands on the rim.
            ux = sx + 2 + (k % 8)
            uy = sy + 4 + (k // 8)
            if not (2 <= ux < size - 2 and 2 <= uy < size - 2):
                continue
            kind = ("JEEP", "MTNK", "LTNK", "APC")[k % 4]
            lines.append("%d=%s,%s,256,%d,0,Hunt,None" % (n, side, kind, cell(ux, uy, stride)))
            n += 1
    lines.append("")

    lines.append("[INFANTRY]")
    n = 0
    for i, (sx, sy) in enumerate(starts):
        side = SIDES[i % len(SIDES)]
        for k in range(3):
            lines.append("%03d=%s,E1,256,%d,%d,Guard,0,None"
                         % (n, side, cell(sx - 2 + k, sy - 2, stride), k))
            n += 1
    lines.append("")

    lines.append("[TERRAIN]")
    lines.append("")
    lines.append("[SMUDGE]")
    lines.append("")

    os.makedirs(outdir, exist_ok=True)
    ini = os.path.join(outdir, name + ".INI")
    with open(ini, "w") as f:
        f.write("\n".join(lines) + "\n")
    write_bin(os.path.join(outdir, name + ".BIN"), tiles, stride)
    write_hgt(os.path.join(outdir, name + ".HGT"), size)

    print("%s: %dx%d, stride %d, %d players, %d non-clear cells, %d structures, %d units"
          % (name, size, size, stride, houses, len(tiles), 2 * houses, (2 + army) * houses))
    for i, (sx, sy) in enumerate(starts):
        print("   start %d at %d,%d (cell %d)" % (i, sx, sy, cell(sx, sy, stride)))


def main():
    a = sys.argv[1:]
    if len(a) < 3:
        sys.exit(__doc__)
    outdir, name, size = a[0], a[1], int(a[2])
    stride, houses, army, pair = DEFAULT_STRIDE, 2, 1, 0
    i = 3
    while i < len(a):
        if a[i] == "--stride":
            stride = int(a[i + 1]); i += 2
        elif a[i] == "--houses":
            houses = int(a[i + 1]); i += 2
        elif a[i] == "--army":
            army = int(a[i + 1]); i += 2
        elif a[i] == "--pair":
            pair = int(a[i + 1]); i += 2
        else:
            sys.exit("unknown argument %s" % a[i])
    build(outdir, name, size, stride, houses, army, pair)


if __name__ == "__main__":
    main()
