#!/bin/sh
# Write launcher/lcfg.h: the build number, and where the launcher looks for builds.
#
# NORMALLY THERE IS NOTHING TO CONFIGURE. The launcher reads cnc3dgame.com's own
# Builds section (`/api/builds`, `/api/changelog`, `/api/download?asset=`), which
# is the same data the website's Builds page draws, so there is no separate host
# to stand up, no key to ship and nothing to keep in step. This script exists to
# stamp the build number in, and to let a build be pointed somewhere else.
#
#   tools/launcher/make-config.sh
#       the ordinary case: the site, and the number from VERSION.
#
#   CNC3D_SITE=http://127.0.0.1:3000 tools/launcher/make-config.sh
#       point a launcher at a staging deployment, a local `next dev`, or the fake
#       site tools/launcher/selftest.sh runs. That is the only reason to set it.
#
#   ~/.cnc3d-update, if it exists, is read for the same two values:
#       site  https://staging.example.com
#       key   <sent as X-CNC3D-Key on every request>
#
# THE KEY IS OPTIONAL AND IS NORMALLY EMPTY. cnc3dgame.com does not ask for one:
# it proxies the private repo's release assets itself, so the launcher holds no
# credential. The header is still sent when a key is set, so that gating the
# downloads later is a change to the site and a rebuild, not a rewrite.
set -e
cd "$(dirname "$0")/../.."

CONF="${CNC3D_UPDATE_CONF:-$HOME/.cnc3d-update}"
SITE="${CNC3D_SITE:-${CNC3D_UPDATE_BASE:-}}"
KEY="${CNC3D_UPDATE_KEY:-}"

if [ -z "$SITE" ] && [ -f "$CONF" ]; then
    SITE=$(awk '$1=="site"||$1=="base"{print $2; exit}' "$CONF")
    KEY=$(awk '$1=="key"{print $2; exit}' "$CONF")
fi

# An override that is not https is refused unless it is plainly a local test
# server. A key rides in a header, and a header over plain http is a key handed to
# anyone on the wire; more to the point, an http override that reached a shipped
# build would send every player's update check over the open network.
case "$SITE" in
    "") ;;
    https://*) ;;
    http://localhost*|http://127.0.0.1*) ;;
    *)
        echo "the site override must be https (got: $SITE)" >&2
        exit 1
        ;;
esac

# THE BUILD STRING, from tools/version.sh, which is the only thing that reads the
# VERSION file. It is the launcher's FALLBACK answer to "which build is this": a
# release package carries cnc3d-install.txt and that wins, because it describes
# the install rather than the launcher, but a folder built straight out of the
# tree has no install record and would otherwise show a question mark.
#
# The BARE form, not --release, so the same rule the menu plate follows applies
# here: a tree that is not exactly the released commit stamps itself
# v0.6.2+09447d6-dirty rather than claiming to be v0.6.2, because the first thing
# a bug report has to settle is which code was running. CNC3D_BUILD_ID overrides
# it, which is how tools/release.sh pins the number on the tree it is about to
# commit and tag.
BUILD="${CNC3D_BUILD_ID:-$(sh tools/version.sh 2>/dev/null || true)}"
[ -n "$BUILD" ] || BUILD="?"

# C string escaping for values that should never need it, done rather than
# assumed: a stray quote here would produce a header that does not compile, and
# the error would point at a generated file nobody wrote.
esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

cat > launcher/lcfg.h <<EOF
/* GENERATED by tools/launcher/make-config.sh. Do not edit and do not commit:
   it is rewritten by every launcher build, from the VERSION file at the repo
   root. An empty LCFG_BASE means the default, which is https://cnc3dgame.com. */
#ifndef LCFG_H
#define LCFG_H
#define LCFG_BASE "$(esc "$SITE")"
#define LCFG_KEY "$(esc "$KEY")"
#define LCFG_BUILD "$(esc "${BUILD#v}")"
#endif
EOF

if [ -n "$SITE" ]; then
    echo "launcher/lcfg.h: v${BUILD#v}, builds from $SITE (an override)"
else
    echo "launcher/lcfg.h: v${BUILD#v}, builds from cnc3dgame.com"
fi
