#!/usr/bin/env python3
"""
w98box.py -- get a build onto the Windows 98 machine, run it, and read the result back.

THIS FILE IS THE DEVELOPMENT LOOP FOR THIS BRANCH. Without it there is no way to put a
binary on the box or get a screenshot off it, so it lives in the repo rather than in
somebody's scratch directory. Every awkward thing in here is awkward for a reason that
was found the hard way; the comments say which.

    from w98box import deploy, run, fetch
    deploy(["build/win98/w98glide.exe", "tools/win98/regression.script"])
    hung, report = run("", frames=4000)
    fetch(["r01_start.bmp"])

Or from a shell:

    tools/win98/w98box.py deploy build/win98/w98glide.exe
    tools/win98/w98box.py run 4000
    tools/win98/w98box.py fetch r01_start.bmp
    tools/win98/w98box.py pulldata          copy data/dosdata to the box (needed for sound)

DEPENDENCY: `w98.py`, the AutoIt daemon client, which is NOT part of this repo (it is
shared, and it serves every project that touches that machine). It is kept at
`~/Documents/GamedevTycoon/w98.py` and on the share at `GameBrowser/tools/w98.py`. The
daemon itself listens on 192.168.1.115:9855 and autostarts with Windows.
"""
import os, shutil, sys, time

def _root():
    """The repository root. CNC3D_ROOT wins so a second worktree can be pointed at;
    otherwise it is derived from this file's own location, which makes the script
    portable to any checkout rather than to one home directory."""
    return os.environ.get("CNC3D_ROOT") or os.path.abspath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

for _p in (os.path.expanduser("~/Documents/GamedevTycoon"),
           os.environ.get("W98_TOOLS", "")):
    if os.path.isdir(_p) and _p not in sys.path:
        sys.path.insert(0, _p)
try:
    from w98 import cmd, push
except ImportError:
    sys.exit("w98.py not found. It is the AutoIt daemon client and is not in this repo; "
             "see the module docstring for where it lives.")

# The share is a SINGLE-LEVEL drop folder on purpose: two-level UNC subfolders flake on
# this machine, and COMMAND.COM's `copy` from C: to a UNC path silently fails outright
# ("0 file(s) copied"), which is why every transfer below goes through a pushed AutoIt
# script rather than through the shell.
DROP = os.environ.get("W98_DROP", "")   # the share's drop folder, per machine
UNC  = r"\\192.168.1.117\share\cnc98"
DEST = r"C:\CNC98"
EXE  = "w98glide.exe"
REPORT = "w98glide.txt"


def _au3(lines, remote, marker):
    """Push a generated AutoIt script and RUNWAIT it, then confirm its marker file.

    RUNWAIT on a real exe like AutoIt3.exe is safe. RUNWAIT on a COMMAND.COM job is NOT:
    Windows 98 leaves the DOS box as "Finished - x", RunWait never returns, port 9855
    stops answering and recovery needs VNC. Never do that.
    """
    body = "; generated by tools/win98/w98box.py\n" + "\n".join(lines) + \
           '\nFileWrite("%s\\%s", "ok")\n' % (DEST, marker)
    tmp = "/tmp/w98box_%s.au3" % marker.split(".")[0]
    open(tmp, "w").write(body)
    cmd("DELETE|%s\\%s" % (DEST, marker))
    push(tmp, r"C:\AGENT\%s" % os.path.basename(tmp))
    cmd(r"RUNWAIT|C:\AUTOIT3\AutoIt3.exe C:\AGENT\%s" % os.path.basename(tmp))
    return cmd("EXISTS|%s\\%s" % (DEST, marker)).strip() == "1"


def deploy(files, verbose=True):
    """Mac -> SMB drop -> C:\\CNC98, and REFUSE to lie about it if a file did not land."""
    names, sizes = [], {}
    for f in files:
        if not os.path.exists(f):
            sys.exit("missing: " + f)
        n = os.path.basename(f)
        shutil.copy2(f, os.path.join(DROP, n))
        names.append(n)
        sizes[n] = os.path.getsize(f)

    # A RUNNING binary cannot be overwritten, and FileCopy does not say so. The copy
    # reports success, the size on the box does not change, and the next test silently
    # measures the OLD build. That happened once and cost a confusing half hour, so the
    # running process is closed first and every size is checked afterwards.
    for n in names:
        if n.lower().endswith(".exe") and cmd("PROCEXISTS|" + n).strip() == "1":
            if verbose:
                print("   (closing running %s)" % n)
            cmd("PROCCLOSE|" + n)
            time.sleep(2)

    _au3(['FileCopy("%s\\%s", "%s\\%s", 1)' % (UNC, n, DEST, n) for n in names],
         "copy.au3", "copy.done")

    bad = 0
    for n in names:
        got = cmd("FILESIZE|%s\\%s" % (DEST, n)).strip()
        ok = (got == str(sizes[n]))
        bad += 0 if ok else 1
        if verbose:
            print("   %-24s %10s  %s" % (n, got, "ok" if ok else
                                         "MISMATCH (want %d)" % sizes[n]))
    if bad:
        sys.exit("%d file(s) did not land; refusing to pretend the build is on the box" % bad)
    return names


def fetch(names, outdir="."):
    """C:\\CNC98 -> SMB drop -> local. This is the only way to see this card's output:
    a Voodoo 2 bypasses the 2D adapter entirely, so VNC shows the desktop underneath the
    game and a framebuffer read-back written to a BMP is the whole of the evidence."""
    _au3(['FileCopy("%s\\%s", "%s\\%s", 1)' % (DEST, n, UNC, n) for n in names],
         "fetch.au3", "fetch.done")
    out = []
    for n in names:
        src = os.path.join(DROP, n)
        if os.path.exists(src):
            dst = os.path.join(outdir, n)
            shutil.copy2(src, dst)
            out.append(dst)
            print("   fetched %-24s %d bytes" % (n, os.path.getsize(dst)))
        else:
            print("   MISSING  %s" % n)
    return out


def run(args="", frames=300, wait=40, exe=EXE, report=REPORT):
    """Run the game and return (hung, report_text).

    `hung` is the answer that matters. A wedged Voodoo leaves the process alive with a
    frozen picture and NOTHING else on disk, so "did the report get its final line" is the
    only signal there is. Add `trace` or `trace2` to args to find out where it stopped.
    """
    cmd("DELETE|%s\\%s" % (DEST, report))
    cmd("RUN|%s\\%s %d %s" % (DEST, exe, frames, args))
    for _ in range(wait):
        time.sleep(2)
        if cmd("EXISTS|%s\\%s" % (DEST, report)).strip() == "1" and \
           cmd("PROCEXISTS|" + exe).strip() == "0":
            break
    hung = cmd("PROCEXISTS|" + exe).strip() == "1"
    if hung:
        cmd("PROCCLOSE|" + exe)
        time.sleep(2)
    return hung, cmd("READFILE|%s\\%s" % (DEST, report))


def missions(names, root=None):
    """Put scenario .INI and .BIN files into C:\\CNC98\\missions\\.

    deploy() cannot: it copies flat into DEST by basename, and the brain reads its
    scenarios from a SUBDIRECTORY (tier1/w98_glidegame.c builds "%smissions\\" and hands
    it to wb_start). Deploying a mission with deploy() therefore lands it one level too
    high and the engine fails to start with no diagnostic worth reading.

    `root` defaults to the MAIN worktree's mission set, which is where the scenarios
    actually live -- this branch's copy of game/missions is older and does not have all
    of them.
    """
    root = root or os.path.join(_root(), "game", "missions")
    dest = DEST + r"\missions"
    _au3(['DirCreate("%s")' % dest], "mkmis.au3", "mkmis.done")
    ok = True
    for n in names:
        src = os.path.join(root, n)
        if not os.path.exists(src):
            print("   MISSING locally: " + n); ok = False; continue
        shutil.copy2(src, os.path.join(DROP, n))
        _au3(['FileCopy("%s\\%s", "%s\\%s", 1)' % (UNC, n, dest, n)], "mis.au3", "mis.done")
        got = cmd("FILESIZE|%s\\%s" % (dest, n)).strip()
        want = str(os.path.getsize(src))
        print("   missions\\%-16s %8s  %s" % (n, got, "ok" if got == want else "MISMATCH want " + want))
        if got != want: ok = False
    return ok


def pullmovies(names=None, root=None):
    """Copy the VQA movies onto the box.

    NOT all of them: data/dosdata/movies is 429 MB and the one shipping scenario needs
    four (plus the logo reel for the menu's Intro item). They go through the same SMB drop
    and the same FileCopy every other transfer uses, and the size is checked on the far
    side rather than assumed -- a truncated movie decodes for a while and then stops,
    which looks exactly like a decoder bug.
    """
    root = root or os.path.join(_root(), "data", "dosdata", "movies")
    names = names or ["GDI1.VQA", "LANDING.VQA", "CONSYARD.VQA", "GAMEOVER.VQA",
                      "LOGO.VQA"]
    dest = DEST + r"\dosdata\movies"
    # The daemon has no MKDIR; AutoIt's DirCreate does, and FileCopy will not make a
    # missing directory for you -- it just reports success and copies nothing, which is
    # the exact failure mode the two-level UNC path already taught this branch once.
    _au3(['DirCreate("%s")' % dest], "mkdir.au3", "mkdir.done")
    ok = True
    for n in names:
        src = os.path.join(root, n)
        if not os.path.exists(src):
            print("   MISSING locally: " + n); ok = False; continue
        shutil.copy2(src, os.path.join(DROP, n))
        _au3(['FileCopy("%s\\%s", "%s\\%s", 1)' % (UNC, n, dest, n)],
             "mov.au3", "mov.done")
        got = cmd("FILESIZE|%s\\%s" % (dest, n)).strip()
        want = str(os.path.getsize(src))
        print("   %-16s %12s  %s" % (n, got, "ok" if got == want else "MISMATCH want " + want))
        if got != want: ok = False
        try:
            os.remove(os.path.join(DROP, n))
        except OSError:
            pass
    return ok


def pulldata(root=None):
    """Copy data/dosdata's archives to the box. Sound needs them and they are 68 MB, so
    this is separate from deploy() and is a once-per-machine job. About 50 seconds."""
    root = root or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    src = os.path.join(root, "data", "dosdata")
    if not os.path.isdir(src):
        sys.exit("no %s" % src)
    os.makedirs(os.path.join(DROP, "dosdata", "transit"), exist_ok=True)
    for f in sorted(os.listdir(src)):
        if f.upper().endswith(".MIX"):
            shutil.copy2(os.path.join(src, f), os.path.join(DROP, "dosdata", f))
            print("   staged %s" % f)
    tr = os.path.join(src, "transit", "TRANSIT.MIX")
    if os.path.exists(tr):
        shutil.copy2(tr, os.path.join(DROP, "dosdata", "transit", "TRANSIT.MIX"))
    _au3([r'DirCreate("%s\dosdata")' % DEST,
          r'DirCreate("%s\dosdata\transit")' % DEST,
          r'FileCopy("%s\dosdata\*.MIX", "%s\dosdata\", 1)' % (UNC, DEST),
          r'FileCopy("%s\dosdata\transit\TRANSIT.MIX", "%s\dosdata\transit\TRANSIT.MIX", 1)'
          % (UNC, DEST)],
         "pull.au3", "pull.done")
    print(cmd("SHELL|dir %s\\dosdata" % DEST))


def play_ready():
    """Leave the box able to take a REAL mouse.

    With an input.script beside the exe the game reads its input from that file and
    ignores the hardware entirely, which from the chair looks exactly like the mouse
    being broken. Always call this before handing the machine back."""
    cmd("DELETE|%s\\input.script" % DEST)
    still = cmd("EXISTS|%s\\input.script" % DEST).strip()
    print("input.script on the box: %s (must be 0)" % still)
    return still == "0"


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    verb = sys.argv[1]
    if verb == "deploy":
        deploy(sys.argv[2:])
    elif verb == "fetch":
        fetch(sys.argv[2:])
    elif verb == "run":
        hung, rep = run(" ".join(sys.argv[3:]),
                        int(sys.argv[2]) if len(sys.argv) > 2 else 300)
        print(rep)
        print("HUNG" if hung else "completed")
    elif verb == "pulldata":
        pulldata()
    elif verb == "playready":
        play_ready()
    else:
        sys.exit(__doc__)
