#!/usr/bin/env python3
"""gen_editor_font.py -- bake a proportional font for the mission editor.

WHY THIS EXISTS

The editor drew every word with C&C's FONT.SHP: an 8x11 fixed-cell bitmap, caps only,
scaled by whole numbers. That is the right font for the 1995 sidebar and the wrong one
for a tool -- every glyph the same width, nothing between 1x and 2x, and the project owner reported
the result three times: "UI text is still VERY uneven and in many places unreadable."

So the editor gets a real face: DejaVu Sans (Bitstream Vera license -- free to embed and
redistribute; the license text ships inside every DejaVu TTF's copyright field), baked at
a ladder of pixel sizes into grayscale atlases and drawn 1:1 with no scaling at all.
Text asks for a size, the runtime snaps to the nearest rung, and both measuring and
drawing use the same rung -- so nothing can misalign the way measure-at-one-scale,
draw-at-another did with the old font.

Regenerate with:  python3 tools/gen_editor_font.py   ->  game/edit_font_data.h
"""

import os, sys, glob

from PIL import Image, ImageDraw, ImageFont

# The ladder. Chosen against the panel's own scale: the layout multiplies design units
# by S in [0.62 .. 2.7], and the old font's request "scale s" meant glyphs ~11*s px tall.
# The runtime maps s -> px = round(10.5 * s) and snaps to these.
SIZES_REG  = [11, 13, 15, 17, 20, 23, 26, 30, 34]
SIZES_BOLD = [13, 15, 17, 20, 23, 26, 30, 34, 38]

CHARS = [chr(c) for c in range(32, 127)]

def find_font(bold):
    names = ["DejaVuSans-Bold.ttf"] if bold else ["DejaVuSans.ttf"]
    roots = []
    try:
        import matplotlib
        roots.append(os.path.join(matplotlib.get_data_path(), "fonts", "ttf"))
    except ImportError:
        pass
    roots += ["/usr/share/fonts/truetype/dejavu", "/Library/Fonts", os.path.expanduser("~/Library/Fonts")]
    for r in roots:
        for n in names:
            p = os.path.join(r, n)
            if os.path.isfile(p):
                return p
    sys.exit("no DejaVu Sans found -- install matplotlib or drop the TTFs in /Library/Fonts")

def bake(path, px):
    """One size -> (atlas Image, per-glyph metrics, ascent, cap height)."""
    font = ImageFont.truetype(path, px)
    ascent, descent = font.getmetrics()
    # Cap height measured off the real 'H', not assumed from the em square.
    hbox = font.getbbox("H")
    caph = hbox[3] - hbox[1]

    glyphs = []
    for ch in CHARS:
        box = font.getbbox(ch)          # (x0, y0, x1, y1) relative to draw origin
        adv = font.getlength(ch)
        w = max(0, box[2] - box[0])
        h = max(0, box[3] - box[1])
        glyphs.append({"ch": ch, "box": box, "adv": adv, "w": w, "h": h})

    # Shelf-pack into a fixed-width atlas.
    AW = 256 if px <= 20 else 512
    x = y = shelf = 0
    for g in glyphs:
        gw, gh = g["w"] + 1, g["h"] + 1
        if x + gw > AW:
            x = 0
            y += shelf
            shelf = 0
        g["ax"], g["ay"] = x, y
        x += gw
        shelf = max(shelf, gh)
    AH = y + shelf
    # Round the height up to something GL 1.1 will take everywhere: power of two.
    p2 = 1
    while p2 < AH:
        p2 *= 2
    AH = p2

    img = Image.new("L", (AW, AH), 0)
    d = ImageDraw.Draw(img)
    for g in glyphs:
        if g["w"] == 0 or g["h"] == 0:
            continue
        # Draw so the glyph's inked box lands exactly at (ax, ay).
        d.text((g["ax"] - g["box"][0], g["ay"] - g["box"][1]), g["ch"], font=font, fill=255)
    return img, glyphs, ascent, caph

def emit(w, path_reg, path_bold):
    w("/* ====================================================================================")
    w(" *  edit_font_data.h -- GENERATED by tools/gen_editor_font.py. Do not edit by hand.")
    w(" *")
    w(" *  DejaVu Sans, baked to grayscale atlases at a ladder of pixel sizes and drawn 1:1.")
    w(" *  Face: Bitstream Vera / DejaVu -- the license permits embedding and redistribution.")
    w(" * ==================================================================================== */")
    w("")
    w("#ifndef EDIT_FONT_DATA_H")
    w("#define EDIT_FONT_DATA_H")
    w("")
    w("struct EfGlyph { unsigned short ax, ay; unsigned char w, h; signed char xo, yo; float adv; };")
    w("struct EfSize  { int px; int aw, ah; int ascent, caph; const unsigned char* atlas;")
    w("                 const EfGlyph* glyph; };")
    w("")
    total = 0
    for wi, (path, sizes, tag) in enumerate([(path_reg, SIZES_REG, "reg"),
                                             (path_bold, SIZES_BOLD, "bold")]):
        for px in sizes:
            img, glyphs, ascent, caph = bake(path, px)
            data = img.tobytes()
            total += len(data)
            w("static const unsigned char ef_atlas_%s_%d[%d] = {" % (tag, px, len(data)))
            for i in range(0, len(data), 24):
                w("    " + ",".join(str(b) for b in data[i:i+24]) + ",")
            w("};")
            w("static const EfGlyph ef_glyph_%s_%d[95] = {" % (tag, px))
            for g in glyphs:
                w("    {%d,%d,%d,%d,%d,%d,%.3ff}," % (
                    g["ax"], g["ay"], g["w"], g["h"],
                    g["box"][0], g["box"][1], g["adv"]))
            w("};")
            w("static const EfSize ef_size_%s_%d = { %d, %d, %d, %d, %d, ef_atlas_%s_%d, ef_glyph_%s_%d };"
              % (tag, px, px, img.width, img.height, ascent, caph, tag, px, tag, px))
            w("")
        w("static const EfSize* const ef_%s[%d] = {" % (tag, len(sizes)))
        for px in sizes:
            w("    &ef_size_%s_%d," % (tag, px))
        w("};")
        w("#define EF_N_%s %d" % (tag.upper(), len(sizes)))
        w("")
    w("#endif /* EDIT_FONT_DATA_H */")
    return total

def main():
    reg, bold = find_font(False), find_font(True)
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "game", "edit_font_data.h")
    lines = []
    total = emit(lines.append, reg, bold)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s  (%d sizes, %.0f KB of atlas)" % (out, len(SIZES_REG) + len(SIZES_BOLD), total / 1024.0))

if __name__ == "__main__":
    main()
