#!/usr/bin/env python3
"""gen_edit_emblem.py -- bake the GDI eagle into a C header for the editor's title bar.

cnc_eyes writes PNGs and reads none: there is no PNG decoder in it, and the Win98/Voodoo2
target is the reason there is not going to be one. So the emblem is baked, the same way
edit_tables.h bakes the legality tables. One source, no parser.

Source: tools/bakery/sharecopy/assets/png/GDI.png, the cartridge's own emblem. Cropped to
its alpha box, squared about the disc so a spin does not wobble, reduced to 48x48 RGBA.

Run:  python3 tools/gen_edit_emblem.py        # writes game/edit_emblem.h
"""

import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
SRC = os.path.join(ROOT, "tools", "bakery", "sharecopy", "assets", "png", "GDI.png")
OUT = os.path.join(ROOT, "game", "edit_emblem.h")
N = 48


def main():
    im = Image.open(SRC).convert("RGBA")
    # Crop to what is actually drawn, then centre it in a square: a coin spun about its
    # vertical axis wobbles if the art is not centred on that axis.
    box = im.split()[3].getbbox() or (0, 0, im.width, im.height)
    im = im.crop(box)
    side = max(im.size)
    sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    sq.paste(im, ((side - im.width) // 2, (side - im.height) // 2))
    px = sq.resize((N, N), Image.LANCZOS).tobytes()

    L = []
    w = L.append
    w("/* ====================================================================================")
    w(" *  edit_emblem.h -- GENERATED by tools/gen_edit_emblem.py. Do not edit by hand.")
    w(" *")
    w(" *  The GDI eagle for the editor's title bar, straight out of the cartridge's own art")
    w(" *  (GDI.png in the romdump PNG tree). Squared about the disc so it spins on its axis")
    w(" *  without wobbling, then reduced to %dx%d RGBA." % (N, N))
    w(" *")
    w(" *  Baked as an array rather than loaded from a file because cnc_eyes carries no PNG")
    w(" *  DECODER -- it writes them for screenshots and reads none -- and the Win98 target is")
    w(" *  the reason that stays true. Same rule as edit_tables.h: one source, no parser.")
    w(" * ==================================================================================== */")
    w("")
    w("#ifndef EDIT_EMBLEM_H")
    w("#define EDIT_EMBLEM_H")
    w("")
    w("#define EDIT_EMBLEM_N %d" % N)
    w("")
    w("static const unsigned char EDIT_EMBLEM[%d * %d * 4] = {" % (N, N))
    for i in range(0, len(px), 24):
        w("    " + ", ".join(str(b) for b in px[i:i + 24]) + ",")
    w("};")
    w("")
    w("#endif /* EDIT_EMBLEM_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote %s  (%dx%d, %d bytes of pixels)"
          % (os.path.relpath(OUT, ROOT), N, N, len(px)))


if __name__ == "__main__":
    main()
