#!/usr/bin/env python3
"""gen_terrain_tiles.py -- bake the (template, icon) -> atlas slot map into a C header.

WHY THE EDITOR NEEDS THIS

The renderer draws terrain from g_pack.cell, where every cell already carries the atlas
rectangle it samples -- (template, icon) was resolved to UVs at bake time and thrown
away. To PAINT a cell the editor has to go the other way: a template and an icon, chosen
from a palette, back to the rectangle in the atlas that draws it.

That mapping is the cartridge's own TL4/TL8 tables (bank slot -> template, icon) read
backwards, plus the atlas packing that n64_terrain.build_atlas performs. Both are
already in the tree; neither is available to a C program at runtime, and cnc_eyes carries
no JSON parser and is not getting one. So it is baked, exactly like edit_tables.h.

THE ATLAS PACKING, reproduced here so the two cannot drift:

    ids  = [0 .. n4-1] + [1024 .. 1024+n8-1]        BANK8_BASE = 1024
    i    = index into that list  ->  (row, col) = divmod(i, 32)
    x0   = col * 26 + 1,  y0 = row * 26 + 1          PITCH 26 = 24 + 2*GUTTER
    uv   = (x0/uw, y0/uh) .. ((x0+24)/uw, (y0+24)/uh)

uw/uh are the atlas's UNPADDED dimensions, which the pack reports at runtime -- the
texture itself is padded to a power of two and the renderer already scales by uw/w.

Run:  python3 tools/gen_terrain_tiles.py        # writes game/terrain_tiles.h
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
TERRAIN = os.path.join(ROOT, "tools", "bakery", "sharecopy", "assets", "terrain")
sys.path.insert(0, TERRAIN)

import n64_terrain as NT  # noqa: E402

OUT = os.path.join(ROOT, "game", "terrain_tiles.h")
THEATERS = ["TEMPERAT", "DESERT", "WINTER", "SNOW", "SAND"]


def theater_map(name):
    """(template, icon) -> atlas slot index, plus whether the tile shows sea."""
    th = NT.load_theater(name)
    ids = list(range(th["n4"])) + [NT.BANK8_BASE + k for k in range(th["n8"])]
    out = {}
    holes = set()
    for i, tid in enumerate(ids):
        pair = NT.tl_lookup(th, tid)
        if pair is None:
            continue
        tmpl, icon = int(pair[0]), int(pair[1])
        # TL is a bijection over the banks; assert rather than silently keep the last.
        key = (tmpl, icon)
        if key in out:
            raise SystemExit("%s: (%d,%d) maps to two slots, %d and %d"
                             % (name, tmpl, icon, out[key], i))
        out[key] = i
        px = NT.tile_rgba(th, tid)
        if px[..., 3].min() == 0:
            holes.add(i)
    return out, holes, len(ids)


def main():
    data = {}
    for t in THEATERS:
        data[t] = theater_map(t)

    L = []
    w = L.append
    w("/* ====================================================================================")
    w(" *  terrain_tiles.h -- GENERATED by tools/gen_terrain_tiles.py. Do not edit by hand.")
    w(" *")
    w(" *  (template, icon) -> the rectangle in the terrain atlas that draws it, per theater.")
    w(" *")
    w(" *  The renderer resolves this at BAKE time and keeps only the UVs, so the editor")
    w(" *  cannot ask it: painting needs the mapping backwards. It is the cartridge's own")
    w(" *  TL4/TL8 tables read in reverse, plus n64_terrain.build_atlas's packing.")
    w(" * ==================================================================================== */")
    w("")
    w("#ifndef TERRAIN_TILES_H")
    w("#define TERRAIN_TILES_H")
    w("")
    w("#define TT_COLS    32")
    w("#define TT_TS      24")
    w("#define TT_GUTTER   1")
    w("#define TT_PITCH   26")
    w("")
    w("struct TtSlot { unsigned short tmpl; unsigned char icon; unsigned short slot;")
    w("                unsigned char sea; };")
    w("")
    for t in THEATERS:
        m, holes, n = data[t]
        rows = sorted(m.items())
        w("/* %s: %d tiles in the bank, %d of them showing sea. */" % (t, n, len(holes)))
        w("#define TT_%s_N %d" % (t, len(rows)))
        w("#define TT_%s_SLOTS %d" % (t, n))
        w("static const TtSlot TT_%s[TT_%s_N] = {" % (t, t))
        for (tmpl, icon), slot in rows:
            w("    { %d, %d, %d, %d }," % (tmpl, icon, slot, 1 if slot in holes else 0))
        w("};")
        w("")
    w("/* WHICH BANK, BY NAME. Not by the TheaterType enum: that is DESERT=0, JUNGLE=1,")
    w("   TEMPERATE=2, WINTER=3 (defines.h:2058) and getting it backwards drew a desert")
    w("   map out of the temperate bank -- same slot numbers, different tiles, and the")
    w("   atlases are different sizes so even the UVs came out about half right. The pack")
    w("   carries its theater as a STRING, which cannot be silently off by one. */")
    w("static inline const TtSlot* tt_table(const char* theater, int* n)")
    w("{")
    w("    if (theater && (theater[0] == 'D' || theater[0] == 'd')) {")
    w("        *n = TT_DESERT_N; return TT_DESERT;")
    w("    }")
    w("    if (theater && (theater[0] == 'W' || theater[0] == 'w')) {")
    w("        *n = TT_WINTER_N; return TT_WINTER;")
    w("    }")
    w("    /* Two letters for the S theaters: SNOW and (in time) SAND share an initial. */")
    w("    if (theater && (theater[0] == 'S' || theater[0] == 's') &&")
    w("        (theater[1] == 'N' || theater[1] == 'n')) {")
    w("        *n = TT_SNOW_N; return TT_SNOW;")
    w("    }")
    w("    if (theater && (theater[0] == 'S' || theater[0] == 's') &&")
    w("        (theater[1] == 'A' || theater[1] == 'a')) {")
    w("        *n = TT_SAND_N; return TT_SAND;")
    w("    }")
    w("    *n = TT_TEMPERAT_N; return TT_TEMPERAT;")
    w("}")
    w("")
    w("/* The atlas slot a (template, icon) pair draws from, or -1 if this theater has no")
    w("   such tile -- which is a real answer, not an error: the two banks differ. */")
    w("static inline int tt_slot_of(const char* theater, int tmpl, int icon, int* sea)")
    w("{")
    w("    int n = 0;")
    w("    const TtSlot* t = tt_table(theater, &n);")
    w("    for (int i = 0; i < n; i++)")
    w("        if ((int)t[i].tmpl == tmpl && (int)t[i].icon == icon) {")
    w("            if (sea) *sea = (int)t[i].sea;")
    w("            return (int)t[i].slot;")
    w("        }")
    w("    if (sea) *sea = 0;")
    w("    return -1;")
    w("}")
    w("")
    w("/* The atlas rectangle for a slot, in UNPADDED atlas pixels. */")
    w("static inline void tt_slot_rect(int slot, float* x0, float* y0)")
    w("{")
    w("    *x0 = (float)((slot % TT_COLS) * TT_PITCH + TT_GUTTER);")
    w("    *y0 = (float)((slot / TT_COLS) * TT_PITCH + TT_GUTTER);")
    w("}")
    w("")
    w("#endif /* TERRAIN_TILES_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    for t in THEATERS:
        m, holes, n = data[t]
        print("  %-9s %4d (template,icon) pairs over %d bank slots, %d show sea"
              % (t, len(m), n, len(holes)))


if __name__ == "__main__":
    main()
