#!/usr/bin/env python3
"""gen_dosinf_dotable.py -- GENERATE game/dosinf_dotable.h from the brain's own idata.cpp.

WHY THIS IS GENERATED AND NOT WRITTEN.

A DOS infantry strip is addressed strip-locally: the renderer computes
`facenum * stages + stage` against one strip and never sees an SHP frame number. The
Remastered art is indexed the other way, by the SHP frame, so something has to bridge
them -- and the bridge is the engine's own (Frame, Count, Jump) triple per (type, action):

    shp = Frame + facenum * Jump + stage

Those triples exist in exactly one place we control, `bake_dosinfantry.py`, and they are
TRANSCRIPTIONS. That file already says why that is dangerous and cross-checks itself
against idata.cpp for exactly this reason: a wrong row does not crash, it plays the wrong
frames or an off-by-one death, and nobody notices. Transcribing the same 900 numbers a
second time, into a header, would be the same risk taken twice. So they are read out of
the GPL source instead, the way terrain_tiles.h and edit_tables.h are.

Run:  python3 tools/gen_dosinf_dotable.py   ->  game/dosinf_dotable.h
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
IDATA = os.path.join(ROOT, "brain", "vanilla", "tiberiandawn", "idata.cpp")
OUT = os.path.join(ROOT, "game", "dosinf_dotable.h")

sys.path.insert(0, os.path.join(ROOT, "game"))
import bake_dosinfantry as BDI          # the slot map and the type->table name map


def table(src, name):
    m = re.search(r"int\s+%s\[DO_COUNT\]\[3\]\s*=\s*\{(.*?)\n\};" % name, src, re.S)
    if not m:
        return None
    body = re.sub(r"//[^\n]*", "", m.group(1))
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    n = [int(x) for x in re.findall(r"-?\d+", body)]
    return [tuple(n[i:i + 3]) for i in range(0, len(n), 3)]


def main():
    if not os.path.isfile(IDATA):
        sys.exit("gen_dosinf_dotable: %s is not here; brain/vanilla must be checked out"
                 % IDATA)
    src = open(IDATA, errors="ignore").read()

    types = sorted(BDI.IDATA_TABLE_NAME.items())
    rows = []
    for ini, sname in types:
        t = table(src, sname)
        if t is None:
            sys.exit("gen_dosinf_dotable: no %s[DO_COUNT][3] in idata.cpp" % sname)
        rows.append((ini, sname, [t[r] for r in BDI.IDATA_SLOT_ROW]))

    L = []
    w = L.append
    w("/* ====================================================================================")
    w(" *  dosinf_dotable.h -- GENERATED by tools/gen_dosinf_dotable.py. Do not edit by hand.")
    w(" *")
    w(" *  The engine's own (Frame, Count, Jump) per infantry type and action, read out of")
    w(" *  idata.cpp's <Name>Dos[DO_COUNT][3] tables. InfantryClass::Draw_It composes them as")
    w(" *")
    w(" *      shp = Frame + facenum * Jump + Fetch_Stage() %% max(Count, 1)")
    w(" *")
    w(" *  which is the ONLY bridge between a strip-local frame number, which is what this")
    w(" *  renderer computes, and an SHP frame index, which is what the Remastered art is")
    w(" *  keyed by. Jump == 0 means the action is non-directional (the deaths).")
    w(" *")
    w(" *  A row of (0, 0, 0) means the type has no art for that action.")
    w(" * ==================================================================================== */")
    w("")
    w("#ifndef DOSINF_DOTABLE_H")
    w("#define DOSINF_DOTABLE_H")
    w("")
    w("#define DI_SLOT_COUNT %d" % len(BDI.SLOT_NAMES))
    w("")
    w("/* In the order dosinf_mod.h's DA_* enum uses. */")
    w("static const char* const DI_SLOT_NAME[DI_SLOT_COUNT] = {")
    w("    " + ", ".join('"%s"' % s for s in BDI.SLOT_NAMES))
    w("};")
    w("")
    w("struct DiDo { const char* ini; short row[DI_SLOT_COUNT][3]; };")
    w("")
    w("#define DI_TYPE_COUNT %d" % len(rows))
    w("static const DiDo DI_DO[DI_TYPE_COUNT] = {")
    for ini, sname, rr in rows:
        w("    /* %-8s idata.cpp %s */" % (ini, sname))
        w('    { "%s", {' % ini)
        for k in range(0, len(rr), 5):
            w("        " + " ".join("{%d,%d,%d}," % r for r in rr[k:k + 5]))
        w("    } },")
    w("};")
    w("")
    w("/* The rows for one INI name, or NULL. Linear over %d entries; every caller does this"
      % len(rows))
    w("   once per type when a sheet is built, never per frame. */")
    w("static inline const short (*di_do_rows(const char* ini))[3]")
    w("{")
    w("    int i;")
    w("    for (i = 0; i < DI_TYPE_COUNT; i++)")
    w("        if (!strcmp(DI_DO[i].ini, ini)) return DI_DO[i].row;")
    w("    return 0;")
    w("}")
    w("")
    w("#endif /* DOSINF_DOTABLE_H */")

    open(OUT, "w").write("\n".join(L) + "\n")
    print("wrote %s: %d types x %d slots, read from idata.cpp"
          % (os.path.relpath(OUT, ROOT), len(rows), len(BDI.SLOT_NAMES)))


if __name__ == "__main__":
    main()
