#!/bin/sh
# The ONE place a build number comes from.
#
# The file VERSION at the repo root holds the number and nothing else. Everything that
# needs to say which build this is reads it through this script: the menu plate, both
# packagers, the release tag and the changelog check. There is no second copy to forget.
#
#   tools/version.sh              -> the stamped string, e.g. v0.5.1 or v0.5.1+3a1f2c-dirty
#   tools/version.sh --release    -> the bare release string, e.g. v0.5.1 (no sha, no dirty)
#   tools/version.sh --next       -> what the next PATCH build number will be, e.g. 0.5.2
#   tools/version.sh --next-minor -> the next MINOR one, e.g. 0.6.0 (see below)
#   tools/version.sh --header P   -> write a C header defining CNC3D_BUILD to P
#
# WHY THE SHA AND THE DIRTY FLAG. A build made from a working tree that is not exactly the
# released commit must not claim to be that release, or the first bug report of the next
# round is spent finding out which code was actually running. A release build says
# v0.5.1; anything else says what it really is.
set -e
here=$(cd "$(dirname "$0")/.." && pwd)
base=$(cat "$here/VERSION" 2>/dev/null | tr -d '[:space:]')
[ -n "$base" ] || { echo "no VERSION file at $here/VERSION" >&2; exit 1; }

case "$1" in
--next)
    # Increments of 0.0.1, a project rule: every build gets a number.
    echo "$base" | awk -F. '{ printf "%d.%d.%d\n", $1, $2, $3 + 1 }'
    exit 0
    ;;
--next-minor)
    # A MINOR bump, which docs/CHANGELOG.md defines as "a milestone landing (a whole
    # capability that did not exist before)". It is deliberately a separate verb rather
    # than something --next could decide for itself: whether a round is a milestone is a
    # judgement about what shipped, and nothing in a version string can make it.
    echo "$base" | awk -F. '{ printf "%d.%d.0\n", $1, $2 + 1 }'
    exit 0
    ;;
--release)
    echo "v$base"
    exit 0
    ;;
--rcversion)
    # The COMMA form a Windows VERSIONINFO block needs for its fixed FILEVERSION and
    # PRODUCTVERSION fields, which are four 16-bit numbers and cannot hold "v" or a sha.
    # It exists so tools/win/build-win.sh can stamp the resource from the VERSION file
    # rather than from a number typed a second time into the .rc, which is the same rule
    # the menu plate already follows through --header.
    echo "$base" | awk -F. '{ printf "%d,%d,%d,0\n", $1, $2, $3 }'
    exit 0
    ;;
esac

stamp="v$base"
if git -C "$here" rev-parse --git-dir >/dev/null 2>&1; then
    tagged=$(git -C "$here" tag --points-at HEAD 2>/dev/null | grep -x "v$base" || true)
    dirty=""
    git -C "$here" diff --quiet HEAD 2>/dev/null || dirty="-dirty"
    if [ -z "$tagged" ] || [ -n "$dirty" ]; then
        sha=$(git -C "$here" rev-parse --short=7 HEAD 2>/dev/null || echo unknown)
        stamp="v$base+$sha$dirty"
    fi
fi

if [ "$1" = "--header" ]; then
    out="$2"
    [ -n "$out" ] || { echo "--header needs a path" >&2; exit 1; }
    tmp="$out.tmp$$"
    {
        echo "/* GENERATED by tools/version.sh. Do not edit and do not commit: it is"
        echo "   rebuilt by every build script, from the VERSION file at the repo root. */"
        echo "#ifndef CNC3D_BUILD_H"
        echo "#define CNC3D_BUILD_H"
        echo "#define CNC3D_BUILD \"$stamp\""
        echo "#endif"
    } > "$tmp"
    # Only replace it if it changed, so a rebuild does not touch every translation unit
    # that includes it and the staleness gate stays meaningful.
    if [ -f "$out" ] && cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv "$tmp" "$out"; fi
    exit 0
fi

echo "$stamp"
